// Code generated by cmd/codegen; DO NOT EDIT.

package tmdb

import (
	"github.com/thulasirajkomminar/tmdb-go/account"
	"github.com/thulasirajkomminar/tmdb-go/authentication"
	"github.com/thulasirajkomminar/tmdb-go/certification"
	"github.com/thulasirajkomminar/tmdb-go/collection"
	"github.com/thulasirajkomminar/tmdb-go/company"
	"github.com/thulasirajkomminar/tmdb-go/configuration"
	"github.com/thulasirajkomminar/tmdb-go/credit"
	"github.com/thulasirajkomminar/tmdb-go/discover"
	"github.com/thulasirajkomminar/tmdb-go/find"
	"github.com/thulasirajkomminar/tmdb-go/genre"
	"github.com/thulasirajkomminar/tmdb-go/guest"
	"github.com/thulasirajkomminar/tmdb-go/keyword"
	"github.com/thulasirajkomminar/tmdb-go/list"
	"github.com/thulasirajkomminar/tmdb-go/movie"
	"github.com/thulasirajkomminar/tmdb-go/network"
	"github.com/thulasirajkomminar/tmdb-go/person"
	"github.com/thulasirajkomminar/tmdb-go/review"
	"github.com/thulasirajkomminar/tmdb-go/search"
	"github.com/thulasirajkomminar/tmdb-go/trending"
	"github.com/thulasirajkomminar/tmdb-go/tv"
	"github.com/thulasirajkomminar/tmdb-go/watch"
)

// Client aggregates one generated sub-client per TMDB resource family.
// Each field is a ClientWithResponses, exposing both the raw `Foo` methods
// (returning *http.Response) and the typed `FooWithResponse` methods
// (returning *FooResponse with a parsed JSON200 payload).
type Client struct {
	Account        *account.ClientWithResponses
	Authentication *authentication.ClientWithResponses
	Certification  *certification.ClientWithResponses
	Collection     *collection.ClientWithResponses
	Company        *company.ClientWithResponses
	Configuration  *configuration.ClientWithResponses
	Credit         *credit.ClientWithResponses
	Discover       *discover.ClientWithResponses
	Find           *find.ClientWithResponses
	Genre          *genre.ClientWithResponses
	Guest          *guest.ClientWithResponses
	Keyword        *keyword.ClientWithResponses
	List           *list.ClientWithResponses
	Movie          *movie.ClientWithResponses
	Network        *network.ClientWithResponses
	Person         *person.ClientWithResponses
	Review         *review.ClientWithResponses
	Search         *search.ClientWithResponses
	Trending       *trending.ClientWithResponses
	Tv             *tv.ClientWithResponses
	Watch          *watch.ClientWithResponses
}

// fillSubClients populates each sub-client field with the shared config.
func (c *Client) fillSubClients(server string, doer HTTPClient, eds []RequestEditor) {
	c.Account = &account.ClientWithResponses{ClientInterface: &account.Client{
		Server:         server,
		Client:         doer,
		RequestEditors: editors[account.RequestEditorFn](eds),
	}}
	c.Authentication = &authentication.ClientWithResponses{ClientInterface: &authentication.Client{
		Server:         server,
		Client:         doer,
		RequestEditors: editors[authentication.RequestEditorFn](eds),
	}}
	c.Certification = &certification.ClientWithResponses{ClientInterface: &certification.Client{
		Server:         server,
		Client:         doer,
		RequestEditors: editors[certification.RequestEditorFn](eds),
	}}
	c.Collection = &collection.ClientWithResponses{ClientInterface: &collection.Client{
		Server:         server,
		Client:         doer,
		RequestEditors: editors[collection.RequestEditorFn](eds),
	}}
	c.Company = &company.ClientWithResponses{ClientInterface: &company.Client{
		Server:         server,
		Client:         doer,
		RequestEditors: editors[company.RequestEditorFn](eds),
	}}
	c.Configuration = &configuration.ClientWithResponses{ClientInterface: &configuration.Client{
		Server:         server,
		Client:         doer,
		RequestEditors: editors[configuration.RequestEditorFn](eds),
	}}
	c.Credit = &credit.ClientWithResponses{ClientInterface: &credit.Client{
		Server:         server,
		Client:         doer,
		RequestEditors: editors[credit.RequestEditorFn](eds),
	}}
	c.Discover = &discover.ClientWithResponses{ClientInterface: &discover.Client{
		Server:         server,
		Client:         doer,
		RequestEditors: editors[discover.RequestEditorFn](eds),
	}}
	c.Find = &find.ClientWithResponses{ClientInterface: &find.Client{
		Server:         server,
		Client:         doer,
		RequestEditors: editors[find.RequestEditorFn](eds),
	}}
	c.Genre = &genre.ClientWithResponses{ClientInterface: &genre.Client{
		Server:         server,
		Client:         doer,
		RequestEditors: editors[genre.RequestEditorFn](eds),
	}}
	c.Guest = &guest.ClientWithResponses{ClientInterface: &guest.Client{
		Server:         server,
		Client:         doer,
		RequestEditors: editors[guest.RequestEditorFn](eds),
	}}
	c.Keyword = &keyword.ClientWithResponses{ClientInterface: &keyword.Client{
		Server:         server,
		Client:         doer,
		RequestEditors: editors[keyword.RequestEditorFn](eds),
	}}
	c.List = &list.ClientWithResponses{ClientInterface: &list.Client{
		Server:         server,
		Client:         doer,
		RequestEditors: editors[list.RequestEditorFn](eds),
	}}
	c.Movie = &movie.ClientWithResponses{ClientInterface: &movie.Client{
		Server:         server,
		Client:         doer,
		RequestEditors: editors[movie.RequestEditorFn](eds),
	}}
	c.Network = &network.ClientWithResponses{ClientInterface: &network.Client{
		Server:         server,
		Client:         doer,
		RequestEditors: editors[network.RequestEditorFn](eds),
	}}
	c.Person = &person.ClientWithResponses{ClientInterface: &person.Client{
		Server:         server,
		Client:         doer,
		RequestEditors: editors[person.RequestEditorFn](eds),
	}}
	c.Review = &review.ClientWithResponses{ClientInterface: &review.Client{
		Server:         server,
		Client:         doer,
		RequestEditors: editors[review.RequestEditorFn](eds),
	}}
	c.Search = &search.ClientWithResponses{ClientInterface: &search.Client{
		Server:         server,
		Client:         doer,
		RequestEditors: editors[search.RequestEditorFn](eds),
	}}
	c.Trending = &trending.ClientWithResponses{ClientInterface: &trending.Client{
		Server:         server,
		Client:         doer,
		RequestEditors: editors[trending.RequestEditorFn](eds),
	}}
	c.Tv = &tv.ClientWithResponses{ClientInterface: &tv.Client{
		Server:         server,
		Client:         doer,
		RequestEditors: editors[tv.RequestEditorFn](eds),
	}}
	c.Watch = &watch.ClientWithResponses{ClientInterface: &watch.Client{
		Server:         server,
		Client:         doer,
		RequestEditors: editors[watch.RequestEditorFn](eds),
	}}
}
