// Package person provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package person

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	Sec0Scopes sec0ContextKey = "sec0.Scopes"
)

// sec0ContextKey is the context key for sec0 security scheme
type sec0ContextKey string

// ChangesPeopleListParams defines parameters for ChangesPeopleList.
type ChangesPeopleListParams struct {
	EndDate   *openapi_types.Date `form:"end_date,omitempty" json:"end_date,omitempty"`
	Page      *int32              `form:"page,omitempty" json:"page,omitempty"`
	StartDate *openapi_types.Date `form:"start_date,omitempty" json:"start_date,omitempty"`
}

// PopularListParams defines parameters for PopularList.
type PopularListParams struct {
	Language *string `form:"language,omitempty" json:"language,omitempty"`
	Page     *int32  `form:"page,omitempty" json:"page,omitempty"`
}

// DetailsParams defines parameters for Details.
type DetailsParams struct {
	// AppendToResponse comma separated list of endpoints within this namespace, 20 items max
	AppendToResponse *string `form:"append_to_response,omitempty" json:"append_to_response,omitempty"`
	Language         *string `form:"language,omitempty" json:"language,omitempty"`
}

// ChangesParams defines parameters for Changes.
type ChangesParams struct {
	EndDate   *openapi_types.Date `form:"end_date,omitempty" json:"end_date,omitempty"`
	Page      *int32              `form:"page,omitempty" json:"page,omitempty"`
	StartDate *openapi_types.Date `form:"start_date,omitempty" json:"start_date,omitempty"`
}

// CombinedCreditsParams defines parameters for CombinedCredits.
type CombinedCreditsParams struct {
	Language *string `form:"language,omitempty" json:"language,omitempty"`
}

// MovieCreditsParams defines parameters for MovieCredits.
type MovieCreditsParams struct {
	Language *string `form:"language,omitempty" json:"language,omitempty"`
}

// TaggedImagesParams defines parameters for TaggedImages.
type TaggedImagesParams struct {
	Page *int32 `form:"page,omitempty" json:"page,omitempty"`
}

// TvCreditsParams defines parameters for TvCredits.
type TvCreditsParams struct {
	Language *string `form:"language,omitempty" json:"language,omitempty"`
}

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// ChangesPeopleList request
	ChangesPeopleList(ctx context.Context, params *ChangesPeopleListParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// LatestId request
	LatestId(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PopularList request
	PopularList(ctx context.Context, params *PopularListParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// Details request
	Details(ctx context.Context, personId int32, params *DetailsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// Changes request
	Changes(ctx context.Context, personId int32, params *ChangesParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CombinedCredits request
	CombinedCredits(ctx context.Context, personId string, params *CombinedCreditsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ExternalIds request
	ExternalIds(ctx context.Context, personId int32, reqEditors ...RequestEditorFn) (*http.Response, error)

	// Images request
	Images(ctx context.Context, personId int32, reqEditors ...RequestEditorFn) (*http.Response, error)

	// MovieCredits request
	MovieCredits(ctx context.Context, personId int32, params *MovieCreditsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// TaggedImages request
	TaggedImages(ctx context.Context, personId int32, params *TaggedImagesParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// Translations request
	Translations(ctx context.Context, personId int32, reqEditors ...RequestEditorFn) (*http.Response, error)

	// TvCredits request
	TvCredits(ctx context.Context, personId int32, params *TvCreditsParams, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) ChangesPeopleList(ctx context.Context, params *ChangesPeopleListParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewChangesPeopleListRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) LatestId(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewLatestIdRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PopularList(ctx context.Context, params *PopularListParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPopularListRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) Details(ctx context.Context, personId int32, params *DetailsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDetailsRequest(c.Server, personId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) Changes(ctx context.Context, personId int32, params *ChangesParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewChangesRequest(c.Server, personId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CombinedCredits(ctx context.Context, personId string, params *CombinedCreditsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCombinedCreditsRequest(c.Server, personId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ExternalIds(ctx context.Context, personId int32, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewExternalIdsRequest(c.Server, personId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) Images(ctx context.Context, personId int32, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewImagesRequest(c.Server, personId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) MovieCredits(ctx context.Context, personId int32, params *MovieCreditsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewMovieCreditsRequest(c.Server, personId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) TaggedImages(ctx context.Context, personId int32, params *TaggedImagesParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewTaggedImagesRequest(c.Server, personId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) Translations(ctx context.Context, personId int32, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewTranslationsRequest(c.Server, personId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) TvCredits(ctx context.Context, personId int32, params *TvCreditsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewTvCreditsRequest(c.Server, personId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewChangesPeopleListRequest generates requests for ChangesPeopleList
func NewChangesPeopleListRequest(server string, params *ChangesPeopleListParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/3/person/changes")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.EndDate != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "end_date", *params.EndDate, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: "date"}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.Page != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "page", *params.Page, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: "int32"}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.StartDate != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "start_date", *params.StartDate, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: "date"}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewLatestIdRequest generates requests for LatestId
func NewLatestIdRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/3/person/latest")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPopularListRequest generates requests for PopularList
func NewPopularListRequest(server string, params *PopularListParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/3/person/popular")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.Language != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "language", *params.Language, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.Page != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "page", *params.Page, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: "int32"}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewDetailsRequest generates requests for Details
func NewDetailsRequest(server string, personId int32, params *DetailsParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "person_id", personId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "integer", Format: "int32"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/3/person/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.AppendToResponse != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "append_to_response", *params.AppendToResponse, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.Language != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "language", *params.Language, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewChangesRequest generates requests for Changes
func NewChangesRequest(server string, personId int32, params *ChangesParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "person_id", personId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "integer", Format: "int32"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/3/person/%s/changes", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.EndDate != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "end_date", *params.EndDate, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: "date"}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.Page != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "page", *params.Page, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: "int32"}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.StartDate != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "start_date", *params.StartDate, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: "date"}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCombinedCreditsRequest generates requests for CombinedCredits
func NewCombinedCreditsRequest(server string, personId string, params *CombinedCreditsParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "person_id", personId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/3/person/%s/combined_credits", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.Language != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "language", *params.Language, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewExternalIdsRequest generates requests for ExternalIds
func NewExternalIdsRequest(server string, personId int32) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "person_id", personId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "integer", Format: "int32"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/3/person/%s/external_ids", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewImagesRequest generates requests for Images
func NewImagesRequest(server string, personId int32) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "person_id", personId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "integer", Format: "int32"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/3/person/%s/images", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewMovieCreditsRequest generates requests for MovieCredits
func NewMovieCreditsRequest(server string, personId int32, params *MovieCreditsParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "person_id", personId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "integer", Format: "int32"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/3/person/%s/movie_credits", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.Language != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "language", *params.Language, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewTaggedImagesRequest generates requests for TaggedImages
func NewTaggedImagesRequest(server string, personId int32, params *TaggedImagesParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "person_id", personId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "integer", Format: "int32"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/3/person/%s/tagged_images", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.Page != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "page", *params.Page, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: "int32"}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewTranslationsRequest generates requests for Translations
func NewTranslationsRequest(server string, personId int32) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "person_id", personId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "integer", Format: "int32"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/3/person/%s/translations", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewTvCreditsRequest generates requests for TvCredits
func NewTvCreditsRequest(server string, personId int32, params *TvCreditsParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "person_id", personId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "integer", Format: "int32"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/3/person/%s/tv_credits", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.Language != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "language", *params.Language, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// ChangesPeopleListWithResponse request
	ChangesPeopleListWithResponse(ctx context.Context, params *ChangesPeopleListParams, reqEditors ...RequestEditorFn) (*ChangesPeopleListResponse, error)

	// LatestIdWithResponse request
	LatestIdWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*LatestIdResponse, error)

	// PopularListWithResponse request
	PopularListWithResponse(ctx context.Context, params *PopularListParams, reqEditors ...RequestEditorFn) (*PopularListResponse, error)

	// DetailsWithResponse request
	DetailsWithResponse(ctx context.Context, personId int32, params *DetailsParams, reqEditors ...RequestEditorFn) (*DetailsResponse, error)

	// ChangesWithResponse request
	ChangesWithResponse(ctx context.Context, personId int32, params *ChangesParams, reqEditors ...RequestEditorFn) (*ChangesResponse, error)

	// CombinedCreditsWithResponse request
	CombinedCreditsWithResponse(ctx context.Context, personId string, params *CombinedCreditsParams, reqEditors ...RequestEditorFn) (*CombinedCreditsResponse, error)

	// ExternalIdsWithResponse request
	ExternalIdsWithResponse(ctx context.Context, personId int32, reqEditors ...RequestEditorFn) (*ExternalIdsResponse, error)

	// ImagesWithResponse request
	ImagesWithResponse(ctx context.Context, personId int32, reqEditors ...RequestEditorFn) (*ImagesResponse, error)

	// MovieCreditsWithResponse request
	MovieCreditsWithResponse(ctx context.Context, personId int32, params *MovieCreditsParams, reqEditors ...RequestEditorFn) (*MovieCreditsResponse, error)

	// TaggedImagesWithResponse request
	TaggedImagesWithResponse(ctx context.Context, personId int32, params *TaggedImagesParams, reqEditors ...RequestEditorFn) (*TaggedImagesResponse, error)

	// TranslationsWithResponse request
	TranslationsWithResponse(ctx context.Context, personId int32, reqEditors ...RequestEditorFn) (*TranslationsResponse, error)

	// TvCreditsWithResponse request
	TvCreditsWithResponse(ctx context.Context, personId int32, params *TvCreditsParams, reqEditors ...RequestEditorFn) (*TvCreditsResponse, error)
}

type ChangesPeopleListResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Page    *int `json:"page,omitempty"`
		Results *[]struct {
			Adult *bool `json:"adult,omitempty"`
			Id    *int  `json:"id,omitempty"`
		} `json:"results,omitempty"`
		TotalPages   *int `json:"total_pages,omitempty"`
		TotalResults *int `json:"total_results,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r ChangesPeopleListResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ChangesPeopleListResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ChangesPeopleListResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type LatestIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Adult              *bool          `json:"adult,omitempty"`
		AlsoKnownAs        *[]interface{} `json:"also_known_as,omitempty"`
		Biography          *string        `json:"biography,omitempty"`
		Birthday           interface{}    `json:"birthday,omitempty"`
		Deathday           interface{}    `json:"deathday,omitempty"`
		Gender             *int           `json:"gender,omitempty"`
		Homepage           interface{}    `json:"homepage,omitempty"`
		Id                 *int           `json:"id,omitempty"`
		ImdbId             interface{}    `json:"imdb_id,omitempty"`
		KnownForDepartment interface{}    `json:"known_for_department,omitempty"`
		Name               *string        `json:"name,omitempty"`
		PlaceOfBirth       interface{}    `json:"place_of_birth,omitempty"`
		Popularity         *int           `json:"popularity,omitempty"`
		ProfilePath        interface{}    `json:"profile_path,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r LatestIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r LatestIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r LatestIdResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type PopularListResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Page    *int `json:"page,omitempty"`
		Results *[]struct {
			Adult    *bool `json:"adult,omitempty"`
			Gender   *int  `json:"gender,omitempty"`
			Id       *int  `json:"id,omitempty"`
			KnownFor *[]struct {
				Adult            *bool    `json:"adult,omitempty"`
				BackdropPath     *string  `json:"backdrop_path,omitempty"`
				GenreIds         *[]int   `json:"genre_ids,omitempty"`
				Id               *int     `json:"id,omitempty"`
				MediaType        *string  `json:"media_type,omitempty"`
				OriginalLanguage *string  `json:"original_language,omitempty"`
				OriginalTitle    *string  `json:"original_title,omitempty"`
				Overview         *string  `json:"overview,omitempty"`
				PosterPath       *string  `json:"poster_path,omitempty"`
				ReleaseDate      *string  `json:"release_date,omitempty"`
				Title            *string  `json:"title,omitempty"`
				Video            *bool    `json:"video,omitempty"`
				VoteAverage      *float32 `json:"vote_average,omitempty"`
				VoteCount        *int     `json:"vote_count,omitempty"`
			} `json:"known_for,omitempty"`
			KnownForDepartment *string  `json:"known_for_department,omitempty"`
			Name               *string  `json:"name,omitempty"`
			Popularity         *float32 `json:"popularity,omitempty"`
			ProfilePath        *string  `json:"profile_path,omitempty"`
		} `json:"results,omitempty"`
		TotalPages   *int `json:"total_pages,omitempty"`
		TotalResults *int `json:"total_results,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r PopularListResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PopularListResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r PopularListResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type DetailsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Adult              *bool       `json:"adult,omitempty"`
		AlsoKnownAs        *[]string   `json:"also_known_as,omitempty"`
		Biography          *string     `json:"biography,omitempty"`
		Birthday           *string     `json:"birthday,omitempty"`
		Deathday           interface{} `json:"deathday,omitempty"`
		Gender             *int        `json:"gender,omitempty"`
		Homepage           interface{} `json:"homepage,omitempty"`
		Id                 *int        `json:"id,omitempty"`
		ImdbId             *string     `json:"imdb_id,omitempty"`
		KnownForDepartment *string     `json:"known_for_department,omitempty"`
		Name               *string     `json:"name,omitempty"`
		PlaceOfBirth       *string     `json:"place_of_birth,omitempty"`
		Popularity         *float32    `json:"popularity,omitempty"`
		ProfilePath        *string     `json:"profile_path,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r DetailsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DetailsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r DetailsResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type ChangesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Changes *[]struct {
			Items *[]struct {
				Action   *string `json:"action,omitempty"`
				Id       *string `json:"id,omitempty"`
				Iso31661 *string `json:"iso_3166_1,omitempty"`
				Iso6391  *string `json:"iso_639_1,omitempty"`
				Time     *string `json:"time,omitempty"`
				Value    *string `json:"value,omitempty"`
			} `json:"items,omitempty"`
			Key *string `json:"key,omitempty"`
		} `json:"changes,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r ChangesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ChangesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ChangesResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type CombinedCreditsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Cast *[]struct {
			Adult            *bool    `json:"adult,omitempty"`
			BackdropPath     *string  `json:"backdrop_path,omitempty"`
			Character        *string  `json:"character,omitempty"`
			CreditId         *string  `json:"credit_id,omitempty"`
			GenreIds         *[]int   `json:"genre_ids,omitempty"`
			Id               *int     `json:"id,omitempty"`
			MediaType        *string  `json:"media_type,omitempty"`
			Order            *int     `json:"order,omitempty"`
			OriginalLanguage *string  `json:"original_language,omitempty"`
			OriginalTitle    *string  `json:"original_title,omitempty"`
			Overview         *string  `json:"overview,omitempty"`
			Popularity       *float32 `json:"popularity,omitempty"`
			PosterPath       *string  `json:"poster_path,omitempty"`
			ReleaseDate      *string  `json:"release_date,omitempty"`
			Title            *string  `json:"title,omitempty"`
			Video            *bool    `json:"video,omitempty"`
			VoteAverage      *float32 `json:"vote_average,omitempty"`
			VoteCount        *int     `json:"vote_count,omitempty"`
		} `json:"cast,omitempty"`
		Crew *[]struct {
			Adult            *bool    `json:"adult,omitempty"`
			BackdropPath     *string  `json:"backdrop_path,omitempty"`
			CreditId         *string  `json:"credit_id,omitempty"`
			Department       *string  `json:"department,omitempty"`
			GenreIds         *[]int   `json:"genre_ids,omitempty"`
			Id               *int     `json:"id,omitempty"`
			Job              *string  `json:"job,omitempty"`
			MediaType        *string  `json:"media_type,omitempty"`
			OriginalLanguage *string  `json:"original_language,omitempty"`
			OriginalTitle    *string  `json:"original_title,omitempty"`
			Overview         *string  `json:"overview,omitempty"`
			Popularity       *float32 `json:"popularity,omitempty"`
			PosterPath       *string  `json:"poster_path,omitempty"`
			ReleaseDate      *string  `json:"release_date,omitempty"`
			Title            *string  `json:"title,omitempty"`
			Video            *bool    `json:"video,omitempty"`
			VoteAverage      *float32 `json:"vote_average,omitempty"`
			VoteCount        *int     `json:"vote_count,omitempty"`
		} `json:"crew,omitempty"`
		Id *int `json:"id,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r CombinedCreditsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CombinedCreditsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r CombinedCreditsResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type ExternalIdsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		FacebookId  *string     `json:"facebook_id,omitempty"`
		FreebaseId  *string     `json:"freebase_id,omitempty"`
		FreebaseMid *string     `json:"freebase_mid,omitempty"`
		Id          *int        `json:"id,omitempty"`
		ImdbId      *string     `json:"imdb_id,omitempty"`
		InstagramId *string     `json:"instagram_id,omitempty"`
		TiktokId    *string     `json:"tiktok_id,omitempty"`
		TvrageId    *int        `json:"tvrage_id,omitempty"`
		TwitterId   *string     `json:"twitter_id,omitempty"`
		WikidataId  *string     `json:"wikidata_id,omitempty"`
		YoutubeId   interface{} `json:"youtube_id,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r ExternalIdsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ExternalIdsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ExternalIdsResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type ImagesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Id       *int `json:"id,omitempty"`
		Profiles *[]struct {
			AspectRatio *float32    `json:"aspect_ratio,omitempty"`
			FilePath    *string     `json:"file_path,omitempty"`
			Height      *int        `json:"height,omitempty"`
			Iso6391     interface{} `json:"iso_639_1,omitempty"`
			VoteAverage *float32    `json:"vote_average,omitempty"`
			VoteCount   *int        `json:"vote_count,omitempty"`
			Width       *int        `json:"width,omitempty"`
		} `json:"profiles,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r ImagesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ImagesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ImagesResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type MovieCreditsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Cast *[]struct {
			Adult            *bool    `json:"adult,omitempty"`
			BackdropPath     *string  `json:"backdrop_path,omitempty"`
			Character        *string  `json:"character,omitempty"`
			CreditId         *string  `json:"credit_id,omitempty"`
			GenreIds         *[]int   `json:"genre_ids,omitempty"`
			Id               *int     `json:"id,omitempty"`
			Order            *int     `json:"order,omitempty"`
			OriginalLanguage *string  `json:"original_language,omitempty"`
			OriginalTitle    *string  `json:"original_title,omitempty"`
			Overview         *string  `json:"overview,omitempty"`
			Popularity       *float32 `json:"popularity,omitempty"`
			PosterPath       *string  `json:"poster_path,omitempty"`
			ReleaseDate      *string  `json:"release_date,omitempty"`
			Title            *string  `json:"title,omitempty"`
			Video            *bool    `json:"video,omitempty"`
			VoteAverage      *float32 `json:"vote_average,omitempty"`
			VoteCount        *int     `json:"vote_count,omitempty"`
		} `json:"cast,omitempty"`
		Crew *[]struct {
			Adult            *bool    `json:"adult,omitempty"`
			BackdropPath     *string  `json:"backdrop_path,omitempty"`
			CreditId         *string  `json:"credit_id,omitempty"`
			Department       *string  `json:"department,omitempty"`
			GenreIds         *[]int   `json:"genre_ids,omitempty"`
			Id               *int     `json:"id,omitempty"`
			Job              *string  `json:"job,omitempty"`
			OriginalLanguage *string  `json:"original_language,omitempty"`
			OriginalTitle    *string  `json:"original_title,omitempty"`
			Overview         *string  `json:"overview,omitempty"`
			Popularity       *float32 `json:"popularity,omitempty"`
			PosterPath       *string  `json:"poster_path,omitempty"`
			ReleaseDate      *string  `json:"release_date,omitempty"`
			Title            *string  `json:"title,omitempty"`
			Video            *bool    `json:"video,omitempty"`
			VoteAverage      *float32 `json:"vote_average,omitempty"`
			VoteCount        *int     `json:"vote_count,omitempty"`
		} `json:"crew,omitempty"`
		Id *int `json:"id,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r MovieCreditsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r MovieCreditsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r MovieCreditsResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type TaggedImagesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Id      *int `json:"id,omitempty"`
		Page    *int `json:"page,omitempty"`
		Results *[]struct {
			AspectRatio *float32 `json:"aspect_ratio,omitempty"`
			FilePath    *string  `json:"file_path,omitempty"`
			Height      *int     `json:"height,omitempty"`
			Id          *string  `json:"id,omitempty"`
			ImageType   *string  `json:"image_type,omitempty"`
			Iso6391     *string  `json:"iso_639_1,omitempty"`
			Media       *struct {
				Adult            *bool    `json:"adult,omitempty"`
				BackdropPath     *string  `json:"backdrop_path,omitempty"`
				GenreIds         *[]int   `json:"genre_ids,omitempty"`
				Id               *int     `json:"id,omitempty"`
				MediaType        *string  `json:"media_type,omitempty"`
				OriginalLanguage *string  `json:"original_language,omitempty"`
				OriginalTitle    *string  `json:"original_title,omitempty"`
				Overview         *string  `json:"overview,omitempty"`
				Popularity       *float32 `json:"popularity,omitempty"`
				PosterPath       *string  `json:"poster_path,omitempty"`
				ReleaseDate      *string  `json:"release_date,omitempty"`
				Title            *string  `json:"title,omitempty"`
				Video            *bool    `json:"video,omitempty"`
				VoteAverage      *float32 `json:"vote_average,omitempty"`
				VoteCount        *int     `json:"vote_count,omitempty"`
			} `json:"media,omitempty"`
			MediaType   *string  `json:"media_type,omitempty"`
			VoteAverage *float32 `json:"vote_average,omitempty"`
			VoteCount   *int     `json:"vote_count,omitempty"`
			Width       *int     `json:"width,omitempty"`
		} `json:"results,omitempty"`
		TotalPages   *int `json:"total_pages,omitempty"`
		TotalResults *int `json:"total_results,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r TaggedImagesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r TaggedImagesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r TaggedImagesResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type TranslationsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Id           *int `json:"id,omitempty"`
		Translations *[]struct {
			Data *struct {
				Biography *string `json:"biography,omitempty"`
				Name      *string `json:"name,omitempty"`
			} `json:"data,omitempty"`
			EnglishName *string `json:"english_name,omitempty"`
			Iso31661    *string `json:"iso_3166_1,omitempty"`
			Iso6391     *string `json:"iso_639_1,omitempty"`
			Name        *string `json:"name,omitempty"`
		} `json:"translations,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r TranslationsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r TranslationsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r TranslationsResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type TvCreditsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Cast *[]struct {
			Adult            *bool     `json:"adult,omitempty"`
			BackdropPath     *string   `json:"backdrop_path,omitempty"`
			Character        *string   `json:"character,omitempty"`
			CreditId         *string   `json:"credit_id,omitempty"`
			EpisodeCount     *int      `json:"episode_count,omitempty"`
			FirstAirDate     *string   `json:"first_air_date,omitempty"`
			GenreIds         *[]int    `json:"genre_ids,omitempty"`
			Id               *int      `json:"id,omitempty"`
			Name             *string   `json:"name,omitempty"`
			OriginCountry    *[]string `json:"origin_country,omitempty"`
			OriginalLanguage *string   `json:"original_language,omitempty"`
			OriginalName     *string   `json:"original_name,omitempty"`
			Overview         *string   `json:"overview,omitempty"`
			Popularity       *float32  `json:"popularity,omitempty"`
			PosterPath       *string   `json:"poster_path,omitempty"`
			VoteAverage      *float32  `json:"vote_average,omitempty"`
			VoteCount        *int      `json:"vote_count,omitempty"`
		} `json:"cast,omitempty"`
		Crew *[]struct {
			Adult            *bool     `json:"adult,omitempty"`
			BackdropPath     *string   `json:"backdrop_path,omitempty"`
			CreditId         *string   `json:"credit_id,omitempty"`
			Department       *string   `json:"department,omitempty"`
			EpisodeCount     *int      `json:"episode_count,omitempty"`
			FirstAirDate     *string   `json:"first_air_date,omitempty"`
			GenreIds         *[]int    `json:"genre_ids,omitempty"`
			Id               *int      `json:"id,omitempty"`
			Job              *string   `json:"job,omitempty"`
			Name             *string   `json:"name,omitempty"`
			OriginCountry    *[]string `json:"origin_country,omitempty"`
			OriginalLanguage *string   `json:"original_language,omitempty"`
			OriginalName     *string   `json:"original_name,omitempty"`
			Overview         *string   `json:"overview,omitempty"`
			Popularity       *float32  `json:"popularity,omitempty"`
			PosterPath       *string   `json:"poster_path,omitempty"`
			VoteAverage      *float32  `json:"vote_average,omitempty"`
			VoteCount        *int      `json:"vote_count,omitempty"`
		} `json:"crew,omitempty"`
		Id *int `json:"id,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r TvCreditsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r TvCreditsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r TvCreditsResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// ChangesPeopleListWithResponse request returning *ChangesPeopleListResponse
func (c *ClientWithResponses) ChangesPeopleListWithResponse(ctx context.Context, params *ChangesPeopleListParams, reqEditors ...RequestEditorFn) (*ChangesPeopleListResponse, error) {
	rsp, err := c.ChangesPeopleList(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseChangesPeopleListResponse(rsp)
}

// LatestIdWithResponse request returning *LatestIdResponse
func (c *ClientWithResponses) LatestIdWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*LatestIdResponse, error) {
	rsp, err := c.LatestId(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseLatestIdResponse(rsp)
}

// PopularListWithResponse request returning *PopularListResponse
func (c *ClientWithResponses) PopularListWithResponse(ctx context.Context, params *PopularListParams, reqEditors ...RequestEditorFn) (*PopularListResponse, error) {
	rsp, err := c.PopularList(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePopularListResponse(rsp)
}

// DetailsWithResponse request returning *DetailsResponse
func (c *ClientWithResponses) DetailsWithResponse(ctx context.Context, personId int32, params *DetailsParams, reqEditors ...RequestEditorFn) (*DetailsResponse, error) {
	rsp, err := c.Details(ctx, personId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDetailsResponse(rsp)
}

// ChangesWithResponse request returning *ChangesResponse
func (c *ClientWithResponses) ChangesWithResponse(ctx context.Context, personId int32, params *ChangesParams, reqEditors ...RequestEditorFn) (*ChangesResponse, error) {
	rsp, err := c.Changes(ctx, personId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseChangesResponse(rsp)
}

// CombinedCreditsWithResponse request returning *CombinedCreditsResponse
func (c *ClientWithResponses) CombinedCreditsWithResponse(ctx context.Context, personId string, params *CombinedCreditsParams, reqEditors ...RequestEditorFn) (*CombinedCreditsResponse, error) {
	rsp, err := c.CombinedCredits(ctx, personId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCombinedCreditsResponse(rsp)
}

// ExternalIdsWithResponse request returning *ExternalIdsResponse
func (c *ClientWithResponses) ExternalIdsWithResponse(ctx context.Context, personId int32, reqEditors ...RequestEditorFn) (*ExternalIdsResponse, error) {
	rsp, err := c.ExternalIds(ctx, personId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseExternalIdsResponse(rsp)
}

// ImagesWithResponse request returning *ImagesResponse
func (c *ClientWithResponses) ImagesWithResponse(ctx context.Context, personId int32, reqEditors ...RequestEditorFn) (*ImagesResponse, error) {
	rsp, err := c.Images(ctx, personId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseImagesResponse(rsp)
}

// MovieCreditsWithResponse request returning *MovieCreditsResponse
func (c *ClientWithResponses) MovieCreditsWithResponse(ctx context.Context, personId int32, params *MovieCreditsParams, reqEditors ...RequestEditorFn) (*MovieCreditsResponse, error) {
	rsp, err := c.MovieCredits(ctx, personId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseMovieCreditsResponse(rsp)
}

// TaggedImagesWithResponse request returning *TaggedImagesResponse
func (c *ClientWithResponses) TaggedImagesWithResponse(ctx context.Context, personId int32, params *TaggedImagesParams, reqEditors ...RequestEditorFn) (*TaggedImagesResponse, error) {
	rsp, err := c.TaggedImages(ctx, personId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseTaggedImagesResponse(rsp)
}

// TranslationsWithResponse request returning *TranslationsResponse
func (c *ClientWithResponses) TranslationsWithResponse(ctx context.Context, personId int32, reqEditors ...RequestEditorFn) (*TranslationsResponse, error) {
	rsp, err := c.Translations(ctx, personId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseTranslationsResponse(rsp)
}

// TvCreditsWithResponse request returning *TvCreditsResponse
func (c *ClientWithResponses) TvCreditsWithResponse(ctx context.Context, personId int32, params *TvCreditsParams, reqEditors ...RequestEditorFn) (*TvCreditsResponse, error) {
	rsp, err := c.TvCredits(ctx, personId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseTvCreditsResponse(rsp)
}

// ParseChangesPeopleListResponse parses an HTTP response from a ChangesPeopleListWithResponse call
func ParseChangesPeopleListResponse(rsp *http.Response) (*ChangesPeopleListResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ChangesPeopleListResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Page    *int `json:"page,omitempty"`
			Results *[]struct {
				Adult *bool `json:"adult,omitempty"`
				Id    *int  `json:"id,omitempty"`
			} `json:"results,omitempty"`
			TotalPages   *int `json:"total_pages,omitempty"`
			TotalResults *int `json:"total_results,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseLatestIdResponse parses an HTTP response from a LatestIdWithResponse call
func ParseLatestIdResponse(rsp *http.Response) (*LatestIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &LatestIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Adult              *bool          `json:"adult,omitempty"`
			AlsoKnownAs        *[]interface{} `json:"also_known_as,omitempty"`
			Biography          *string        `json:"biography,omitempty"`
			Birthday           interface{}    `json:"birthday,omitempty"`
			Deathday           interface{}    `json:"deathday,omitempty"`
			Gender             *int           `json:"gender,omitempty"`
			Homepage           interface{}    `json:"homepage,omitempty"`
			Id                 *int           `json:"id,omitempty"`
			ImdbId             interface{}    `json:"imdb_id,omitempty"`
			KnownForDepartment interface{}    `json:"known_for_department,omitempty"`
			Name               *string        `json:"name,omitempty"`
			PlaceOfBirth       interface{}    `json:"place_of_birth,omitempty"`
			Popularity         *int           `json:"popularity,omitempty"`
			ProfilePath        interface{}    `json:"profile_path,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePopularListResponse parses an HTTP response from a PopularListWithResponse call
func ParsePopularListResponse(rsp *http.Response) (*PopularListResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PopularListResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Page    *int `json:"page,omitempty"`
			Results *[]struct {
				Adult    *bool `json:"adult,omitempty"`
				Gender   *int  `json:"gender,omitempty"`
				Id       *int  `json:"id,omitempty"`
				KnownFor *[]struct {
					Adult            *bool    `json:"adult,omitempty"`
					BackdropPath     *string  `json:"backdrop_path,omitempty"`
					GenreIds         *[]int   `json:"genre_ids,omitempty"`
					Id               *int     `json:"id,omitempty"`
					MediaType        *string  `json:"media_type,omitempty"`
					OriginalLanguage *string  `json:"original_language,omitempty"`
					OriginalTitle    *string  `json:"original_title,omitempty"`
					Overview         *string  `json:"overview,omitempty"`
					PosterPath       *string  `json:"poster_path,omitempty"`
					ReleaseDate      *string  `json:"release_date,omitempty"`
					Title            *string  `json:"title,omitempty"`
					Video            *bool    `json:"video,omitempty"`
					VoteAverage      *float32 `json:"vote_average,omitempty"`
					VoteCount        *int     `json:"vote_count,omitempty"`
				} `json:"known_for,omitempty"`
				KnownForDepartment *string  `json:"known_for_department,omitempty"`
				Name               *string  `json:"name,omitempty"`
				Popularity         *float32 `json:"popularity,omitempty"`
				ProfilePath        *string  `json:"profile_path,omitempty"`
			} `json:"results,omitempty"`
			TotalPages   *int `json:"total_pages,omitempty"`
			TotalResults *int `json:"total_results,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseDetailsResponse parses an HTTP response from a DetailsWithResponse call
func ParseDetailsResponse(rsp *http.Response) (*DetailsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DetailsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Adult              *bool       `json:"adult,omitempty"`
			AlsoKnownAs        *[]string   `json:"also_known_as,omitempty"`
			Biography          *string     `json:"biography,omitempty"`
			Birthday           *string     `json:"birthday,omitempty"`
			Deathday           interface{} `json:"deathday,omitempty"`
			Gender             *int        `json:"gender,omitempty"`
			Homepage           interface{} `json:"homepage,omitempty"`
			Id                 *int        `json:"id,omitempty"`
			ImdbId             *string     `json:"imdb_id,omitempty"`
			KnownForDepartment *string     `json:"known_for_department,omitempty"`
			Name               *string     `json:"name,omitempty"`
			PlaceOfBirth       *string     `json:"place_of_birth,omitempty"`
			Popularity         *float32    `json:"popularity,omitempty"`
			ProfilePath        *string     `json:"profile_path,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseChangesResponse parses an HTTP response from a ChangesWithResponse call
func ParseChangesResponse(rsp *http.Response) (*ChangesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ChangesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Changes *[]struct {
				Items *[]struct {
					Action   *string `json:"action,omitempty"`
					Id       *string `json:"id,omitempty"`
					Iso31661 *string `json:"iso_3166_1,omitempty"`
					Iso6391  *string `json:"iso_639_1,omitempty"`
					Time     *string `json:"time,omitempty"`
					Value    *string `json:"value,omitempty"`
				} `json:"items,omitempty"`
				Key *string `json:"key,omitempty"`
			} `json:"changes,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseCombinedCreditsResponse parses an HTTP response from a CombinedCreditsWithResponse call
func ParseCombinedCreditsResponse(rsp *http.Response) (*CombinedCreditsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CombinedCreditsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Cast *[]struct {
				Adult            *bool    `json:"adult,omitempty"`
				BackdropPath     *string  `json:"backdrop_path,omitempty"`
				Character        *string  `json:"character,omitempty"`
				CreditId         *string  `json:"credit_id,omitempty"`
				GenreIds         *[]int   `json:"genre_ids,omitempty"`
				Id               *int     `json:"id,omitempty"`
				MediaType        *string  `json:"media_type,omitempty"`
				Order            *int     `json:"order,omitempty"`
				OriginalLanguage *string  `json:"original_language,omitempty"`
				OriginalTitle    *string  `json:"original_title,omitempty"`
				Overview         *string  `json:"overview,omitempty"`
				Popularity       *float32 `json:"popularity,omitempty"`
				PosterPath       *string  `json:"poster_path,omitempty"`
				ReleaseDate      *string  `json:"release_date,omitempty"`
				Title            *string  `json:"title,omitempty"`
				Video            *bool    `json:"video,omitempty"`
				VoteAverage      *float32 `json:"vote_average,omitempty"`
				VoteCount        *int     `json:"vote_count,omitempty"`
			} `json:"cast,omitempty"`
			Crew *[]struct {
				Adult            *bool    `json:"adult,omitempty"`
				BackdropPath     *string  `json:"backdrop_path,omitempty"`
				CreditId         *string  `json:"credit_id,omitempty"`
				Department       *string  `json:"department,omitempty"`
				GenreIds         *[]int   `json:"genre_ids,omitempty"`
				Id               *int     `json:"id,omitempty"`
				Job              *string  `json:"job,omitempty"`
				MediaType        *string  `json:"media_type,omitempty"`
				OriginalLanguage *string  `json:"original_language,omitempty"`
				OriginalTitle    *string  `json:"original_title,omitempty"`
				Overview         *string  `json:"overview,omitempty"`
				Popularity       *float32 `json:"popularity,omitempty"`
				PosterPath       *string  `json:"poster_path,omitempty"`
				ReleaseDate      *string  `json:"release_date,omitempty"`
				Title            *string  `json:"title,omitempty"`
				Video            *bool    `json:"video,omitempty"`
				VoteAverage      *float32 `json:"vote_average,omitempty"`
				VoteCount        *int     `json:"vote_count,omitempty"`
			} `json:"crew,omitempty"`
			Id *int `json:"id,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseExternalIdsResponse parses an HTTP response from a ExternalIdsWithResponse call
func ParseExternalIdsResponse(rsp *http.Response) (*ExternalIdsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ExternalIdsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			FacebookId  *string     `json:"facebook_id,omitempty"`
			FreebaseId  *string     `json:"freebase_id,omitempty"`
			FreebaseMid *string     `json:"freebase_mid,omitempty"`
			Id          *int        `json:"id,omitempty"`
			ImdbId      *string     `json:"imdb_id,omitempty"`
			InstagramId *string     `json:"instagram_id,omitempty"`
			TiktokId    *string     `json:"tiktok_id,omitempty"`
			TvrageId    *int        `json:"tvrage_id,omitempty"`
			TwitterId   *string     `json:"twitter_id,omitempty"`
			WikidataId  *string     `json:"wikidata_id,omitempty"`
			YoutubeId   interface{} `json:"youtube_id,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseImagesResponse parses an HTTP response from a ImagesWithResponse call
func ParseImagesResponse(rsp *http.Response) (*ImagesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ImagesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Id       *int `json:"id,omitempty"`
			Profiles *[]struct {
				AspectRatio *float32    `json:"aspect_ratio,omitempty"`
				FilePath    *string     `json:"file_path,omitempty"`
				Height      *int        `json:"height,omitempty"`
				Iso6391     interface{} `json:"iso_639_1,omitempty"`
				VoteAverage *float32    `json:"vote_average,omitempty"`
				VoteCount   *int        `json:"vote_count,omitempty"`
				Width       *int        `json:"width,omitempty"`
			} `json:"profiles,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseMovieCreditsResponse parses an HTTP response from a MovieCreditsWithResponse call
func ParseMovieCreditsResponse(rsp *http.Response) (*MovieCreditsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &MovieCreditsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Cast *[]struct {
				Adult            *bool    `json:"adult,omitempty"`
				BackdropPath     *string  `json:"backdrop_path,omitempty"`
				Character        *string  `json:"character,omitempty"`
				CreditId         *string  `json:"credit_id,omitempty"`
				GenreIds         *[]int   `json:"genre_ids,omitempty"`
				Id               *int     `json:"id,omitempty"`
				Order            *int     `json:"order,omitempty"`
				OriginalLanguage *string  `json:"original_language,omitempty"`
				OriginalTitle    *string  `json:"original_title,omitempty"`
				Overview         *string  `json:"overview,omitempty"`
				Popularity       *float32 `json:"popularity,omitempty"`
				PosterPath       *string  `json:"poster_path,omitempty"`
				ReleaseDate      *string  `json:"release_date,omitempty"`
				Title            *string  `json:"title,omitempty"`
				Video            *bool    `json:"video,omitempty"`
				VoteAverage      *float32 `json:"vote_average,omitempty"`
				VoteCount        *int     `json:"vote_count,omitempty"`
			} `json:"cast,omitempty"`
			Crew *[]struct {
				Adult            *bool    `json:"adult,omitempty"`
				BackdropPath     *string  `json:"backdrop_path,omitempty"`
				CreditId         *string  `json:"credit_id,omitempty"`
				Department       *string  `json:"department,omitempty"`
				GenreIds         *[]int   `json:"genre_ids,omitempty"`
				Id               *int     `json:"id,omitempty"`
				Job              *string  `json:"job,omitempty"`
				OriginalLanguage *string  `json:"original_language,omitempty"`
				OriginalTitle    *string  `json:"original_title,omitempty"`
				Overview         *string  `json:"overview,omitempty"`
				Popularity       *float32 `json:"popularity,omitempty"`
				PosterPath       *string  `json:"poster_path,omitempty"`
				ReleaseDate      *string  `json:"release_date,omitempty"`
				Title            *string  `json:"title,omitempty"`
				Video            *bool    `json:"video,omitempty"`
				VoteAverage      *float32 `json:"vote_average,omitempty"`
				VoteCount        *int     `json:"vote_count,omitempty"`
			} `json:"crew,omitempty"`
			Id *int `json:"id,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseTaggedImagesResponse parses an HTTP response from a TaggedImagesWithResponse call
func ParseTaggedImagesResponse(rsp *http.Response) (*TaggedImagesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &TaggedImagesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Id      *int `json:"id,omitempty"`
			Page    *int `json:"page,omitempty"`
			Results *[]struct {
				AspectRatio *float32 `json:"aspect_ratio,omitempty"`
				FilePath    *string  `json:"file_path,omitempty"`
				Height      *int     `json:"height,omitempty"`
				Id          *string  `json:"id,omitempty"`
				ImageType   *string  `json:"image_type,omitempty"`
				Iso6391     *string  `json:"iso_639_1,omitempty"`
				Media       *struct {
					Adult            *bool    `json:"adult,omitempty"`
					BackdropPath     *string  `json:"backdrop_path,omitempty"`
					GenreIds         *[]int   `json:"genre_ids,omitempty"`
					Id               *int     `json:"id,omitempty"`
					MediaType        *string  `json:"media_type,omitempty"`
					OriginalLanguage *string  `json:"original_language,omitempty"`
					OriginalTitle    *string  `json:"original_title,omitempty"`
					Overview         *string  `json:"overview,omitempty"`
					Popularity       *float32 `json:"popularity,omitempty"`
					PosterPath       *string  `json:"poster_path,omitempty"`
					ReleaseDate      *string  `json:"release_date,omitempty"`
					Title            *string  `json:"title,omitempty"`
					Video            *bool    `json:"video,omitempty"`
					VoteAverage      *float32 `json:"vote_average,omitempty"`
					VoteCount        *int     `json:"vote_count,omitempty"`
				} `json:"media,omitempty"`
				MediaType   *string  `json:"media_type,omitempty"`
				VoteAverage *float32 `json:"vote_average,omitempty"`
				VoteCount   *int     `json:"vote_count,omitempty"`
				Width       *int     `json:"width,omitempty"`
			} `json:"results,omitempty"`
			TotalPages   *int `json:"total_pages,omitempty"`
			TotalResults *int `json:"total_results,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseTranslationsResponse parses an HTTP response from a TranslationsWithResponse call
func ParseTranslationsResponse(rsp *http.Response) (*TranslationsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &TranslationsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Id           *int `json:"id,omitempty"`
			Translations *[]struct {
				Data *struct {
					Biography *string `json:"biography,omitempty"`
					Name      *string `json:"name,omitempty"`
				} `json:"data,omitempty"`
				EnglishName *string `json:"english_name,omitempty"`
				Iso31661    *string `json:"iso_3166_1,omitempty"`
				Iso6391     *string `json:"iso_639_1,omitempty"`
				Name        *string `json:"name,omitempty"`
			} `json:"translations,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseTvCreditsResponse parses an HTTP response from a TvCreditsWithResponse call
func ParseTvCreditsResponse(rsp *http.Response) (*TvCreditsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &TvCreditsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Cast *[]struct {
				Adult            *bool     `json:"adult,omitempty"`
				BackdropPath     *string   `json:"backdrop_path,omitempty"`
				Character        *string   `json:"character,omitempty"`
				CreditId         *string   `json:"credit_id,omitempty"`
				EpisodeCount     *int      `json:"episode_count,omitempty"`
				FirstAirDate     *string   `json:"first_air_date,omitempty"`
				GenreIds         *[]int    `json:"genre_ids,omitempty"`
				Id               *int      `json:"id,omitempty"`
				Name             *string   `json:"name,omitempty"`
				OriginCountry    *[]string `json:"origin_country,omitempty"`
				OriginalLanguage *string   `json:"original_language,omitempty"`
				OriginalName     *string   `json:"original_name,omitempty"`
				Overview         *string   `json:"overview,omitempty"`
				Popularity       *float32  `json:"popularity,omitempty"`
				PosterPath       *string   `json:"poster_path,omitempty"`
				VoteAverage      *float32  `json:"vote_average,omitempty"`
				VoteCount        *int      `json:"vote_count,omitempty"`
			} `json:"cast,omitempty"`
			Crew *[]struct {
				Adult            *bool     `json:"adult,omitempty"`
				BackdropPath     *string   `json:"backdrop_path,omitempty"`
				CreditId         *string   `json:"credit_id,omitempty"`
				Department       *string   `json:"department,omitempty"`
				EpisodeCount     *int      `json:"episode_count,omitempty"`
				FirstAirDate     *string   `json:"first_air_date,omitempty"`
				GenreIds         *[]int    `json:"genre_ids,omitempty"`
				Id               *int      `json:"id,omitempty"`
				Job              *string   `json:"job,omitempty"`
				Name             *string   `json:"name,omitempty"`
				OriginCountry    *[]string `json:"origin_country,omitempty"`
				OriginalLanguage *string   `json:"original_language,omitempty"`
				OriginalName     *string   `json:"original_name,omitempty"`
				Overview         *string   `json:"overview,omitempty"`
				Popularity       *float32  `json:"popularity,omitempty"`
				PosterPath       *string   `json:"poster_path,omitempty"`
				VoteAverage      *float32  `json:"vote_average,omitempty"`
				VoteCount        *int      `json:"vote_count,omitempty"`
			} `json:"crew,omitempty"`
			Id *int `json:"id,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}
