// Package certification provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package certification

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
)

const (
	Sec0Scopes sec0ContextKey = "sec0.Scopes"
)

// sec0ContextKey is the context key for sec0 security scheme
type sec0ContextKey string

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// MovieList request
	MovieList(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CertificationsTvList request
	CertificationsTvList(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) MovieList(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewMovieListRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CertificationsTvList(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCertificationsTvListRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewMovieListRequest generates requests for MovieList
func NewMovieListRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/3/certification/movie/list")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCertificationsTvListRequest generates requests for CertificationsTvList
func NewCertificationsTvListRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/3/certification/tv/list")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// MovieListWithResponse request
	MovieListWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*MovieListResponse, error)

	// CertificationsTvListWithResponse request
	CertificationsTvListWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*CertificationsTvListResponse, error)
}

type MovieListResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Certifications *struct {
			AR *[]struct {
				Certification *string `json:"certification,omitempty"`
				Meaning       *string `json:"meaning,omitempty"`
				Order         *int    `json:"order,omitempty"`
			} `json:"AR,omitempty"`
			AU *[]struct {
				Certification *string `json:"certification,omitempty"`
				Meaning       *string `json:"meaning,omitempty"`
				Order         *int    `json:"order,omitempty"`
			} `json:"AU,omitempty"`
			BG *[]struct {
				Certification *string `json:"certification,omitempty"`
				Meaning       *string `json:"meaning,omitempty"`
				Order         *int    `json:"order,omitempty"`
			} `json:"BG,omitempty"`
			BR *[]struct {
				Certification *string `json:"certification,omitempty"`
				Meaning       *string `json:"meaning,omitempty"`
				Order         *int    `json:"order,omitempty"`
			} `json:"BR,omitempty"`
			CA *[]struct {
				Certification *string `json:"certification,omitempty"`
				Meaning       *string `json:"meaning,omitempty"`
				Order         *int    `json:"order,omitempty"`
			} `json:"CA,omitempty"`
			CAQC *[]struct {
				Certification *string `json:"certification,omitempty"`
				Meaning       *string `json:"meaning,omitempty"`
				Order         *int    `json:"order,omitempty"`
			} `json:"CA-QC,omitempty"`
			CH *[]struct {
				Certification *string `json:"certification,omitempty"`
				Meaning       *string `json:"meaning,omitempty"`
				Order         *int    `json:"order,omitempty"`
			} `json:"CH,omitempty"`
			DE *[]struct {
				Certification *string `json:"certification,omitempty"`
				Meaning       *string `json:"meaning,omitempty"`
				Order         *int    `json:"order,omitempty"`
			} `json:"DE,omitempty"`
			DK *[]struct {
				Certification *string `json:"certification,omitempty"`
				Meaning       *string `json:"meaning,omitempty"`
				Order         *int    `json:"order,omitempty"`
			} `json:"DK,omitempty"`
			ES *[]struct {
				Certification *string `json:"certification,omitempty"`
				Meaning       *string `json:"meaning,omitempty"`
				Order         *int    `json:"order,omitempty"`
			} `json:"ES,omitempty"`
			FI *[]struct {
				Certification *string `json:"certification,omitempty"`
				Meaning       *string `json:"meaning,omitempty"`
				Order         *int    `json:"order,omitempty"`
			} `json:"FI,omitempty"`
			FR *[]struct {
				Certification *string `json:"certification,omitempty"`
				Meaning       *string `json:"meaning,omitempty"`
				Order         *int    `json:"order,omitempty"`
			} `json:"FR,omitempty"`
			GB *[]struct {
				Certification *string `json:"certification,omitempty"`
				Meaning       *string `json:"meaning,omitempty"`
				Order         *int    `json:"order,omitempty"`
			} `json:"GB,omitempty"`
			GR *[]struct {
				Certification *string `json:"certification,omitempty"`
				Meaning       *string `json:"meaning,omitempty"`
				Order         *int    `json:"order,omitempty"`
			} `json:"GR,omitempty"`
			HK *[]struct {
				Certification *string `json:"certification,omitempty"`
				Meaning       *string `json:"meaning,omitempty"`
				Order         *int    `json:"order,omitempty"`
			} `json:"HK,omitempty"`
			HU *[]struct {
				Certification *string `json:"certification,omitempty"`
				Meaning       *string `json:"meaning,omitempty"`
				Order         *int    `json:"order,omitempty"`
			} `json:"HU,omitempty"`
			ID *[]struct {
				Certification *string `json:"certification,omitempty"`
				Meaning       *string `json:"meaning,omitempty"`
				Order         *int    `json:"order,omitempty"`
			} `json:"ID,omitempty"`
			IE *[]struct {
				Certification *string `json:"certification,omitempty"`
				Meaning       *string `json:"meaning,omitempty"`
				Order         *int    `json:"order,omitempty"`
			} `json:"IE,omitempty"`
			IL *[]struct {
				Certification *string `json:"certification,omitempty"`
				Meaning       *string `json:"meaning,omitempty"`
				Order         *int    `json:"order,omitempty"`
			} `json:"IL,omitempty"`
			IN *[]struct {
				Certification *string `json:"certification,omitempty"`
				Meaning       *string `json:"meaning,omitempty"`
				Order         *int    `json:"order,omitempty"`
			} `json:"IN,omitempty"`
			IT *[]struct {
				Certification *string `json:"certification,omitempty"`
				Meaning       *string `json:"meaning,omitempty"`
				Order         *int    `json:"order,omitempty"`
			} `json:"IT,omitempty"`
			JP *[]struct {
				Certification *string `json:"certification,omitempty"`
				Meaning       *string `json:"meaning,omitempty"`
				Order         *int    `json:"order,omitempty"`
			} `json:"JP,omitempty"`
			KR *[]struct {
				Certification *string `json:"certification,omitempty"`
				Meaning       *string `json:"meaning,omitempty"`
				Order         *int    `json:"order,omitempty"`
			} `json:"KR,omitempty"`
			LT *[]struct {
				Certification *string `json:"certification,omitempty"`
				Meaning       *string `json:"meaning,omitempty"`
				Order         *int    `json:"order,omitempty"`
			} `json:"LT,omitempty"`
			LU *[]struct {
				Certification *string `json:"certification,omitempty"`
				Meaning       *string `json:"meaning,omitempty"`
				Order         *int    `json:"order,omitempty"`
			} `json:"LU,omitempty"`
			LV *[]struct {
				Certification *string `json:"certification,omitempty"`
				Meaning       *string `json:"meaning,omitempty"`
				Order         *int    `json:"order,omitempty"`
			} `json:"LV,omitempty"`
			MO *[]struct {
				Certification *string `json:"certification,omitempty"`
				Meaning       *string `json:"meaning,omitempty"`
				Order         *int    `json:"order,omitempty"`
			} `json:"MO,omitempty"`
			MX *[]struct {
				Certification *string `json:"certification,omitempty"`
				Meaning       *string `json:"meaning,omitempty"`
				Order         *int    `json:"order,omitempty"`
			} `json:"MX,omitempty"`
			MY *[]struct {
				Certification *string `json:"certification,omitempty"`
				Meaning       *string `json:"meaning,omitempty"`
				Order         *int    `json:"order,omitempty"`
			} `json:"MY,omitempty"`
			NL *[]struct {
				Certification *string `json:"certification,omitempty"`
				Meaning       *string `json:"meaning,omitempty"`
				Order         *int    `json:"order,omitempty"`
			} `json:"NL,omitempty"`
			NO *[]struct {
				Certification *string `json:"certification,omitempty"`
				Meaning       *string `json:"meaning,omitempty"`
				Order         *int    `json:"order,omitempty"`
			} `json:"NO,omitempty"`
			NZ *[]struct {
				Certification *string `json:"certification,omitempty"`
				Meaning       *string `json:"meaning,omitempty"`
				Order         *int    `json:"order,omitempty"`
			} `json:"NZ,omitempty"`
			PH *[]struct {
				Certification *string `json:"certification,omitempty"`
				Meaning       *string `json:"meaning,omitempty"`
				Order         *int    `json:"order,omitempty"`
			} `json:"PH,omitempty"`
			PR *[]struct {
				Certification *string `json:"certification,omitempty"`
				Meaning       *string `json:"meaning,omitempty"`
				Order         *int    `json:"order,omitempty"`
			} `json:"PR,omitempty"`
			PT *[]struct {
				Certification *string `json:"certification,omitempty"`
				Meaning       *string `json:"meaning,omitempty"`
				Order         *int    `json:"order,omitempty"`
			} `json:"PT,omitempty"`
			RU *[]struct {
				Certification *string `json:"certification,omitempty"`
				Meaning       *string `json:"meaning,omitempty"`
				Order         *int    `json:"order,omitempty"`
			} `json:"RU,omitempty"`
			SE *[]struct {
				Certification *string `json:"certification,omitempty"`
				Meaning       *string `json:"meaning,omitempty"`
				Order         *int    `json:"order,omitempty"`
			} `json:"SE,omitempty"`
			SG *[]struct {
				Certification *string `json:"certification,omitempty"`
				Meaning       *string `json:"meaning,omitempty"`
				Order         *int    `json:"order,omitempty"`
			} `json:"SG,omitempty"`
			SK *[]struct {
				Certification *string `json:"certification,omitempty"`
				Meaning       *string `json:"meaning,omitempty"`
				Order         *int    `json:"order,omitempty"`
			} `json:"SK,omitempty"`
			TH *[]struct {
				Certification *string `json:"certification,omitempty"`
				Meaning       *string `json:"meaning,omitempty"`
				Order         *int    `json:"order,omitempty"`
			} `json:"TH,omitempty"`
			TR *[]struct {
				Certification *string `json:"certification,omitempty"`
				Meaning       *string `json:"meaning,omitempty"`
				Order         *int    `json:"order,omitempty"`
			} `json:"TR,omitempty"`
			TW *[]struct {
				Certification *string `json:"certification,omitempty"`
				Meaning       *string `json:"meaning,omitempty"`
				Order         *int    `json:"order,omitempty"`
			} `json:"TW,omitempty"`
			US *[]struct {
				Certification *string `json:"certification,omitempty"`
				Meaning       *string `json:"meaning,omitempty"`
				Order         *int    `json:"order,omitempty"`
			} `json:"US,omitempty"`
			VI *[]struct {
				Certification *string `json:"certification,omitempty"`
				Meaning       *string `json:"meaning,omitempty"`
				Order         *int    `json:"order,omitempty"`
			} `json:"VI,omitempty"`
			ZA *[]struct {
				Certification *string `json:"certification,omitempty"`
				Meaning       *string `json:"meaning,omitempty"`
				Order         *int    `json:"order,omitempty"`
			} `json:"ZA,omitempty"`
		} `json:"certifications,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r MovieListResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r MovieListResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r MovieListResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type CertificationsTvListResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Certifications *struct {
			AR *[]struct {
				Certification *string `json:"certification,omitempty"`
				Meaning       *string `json:"meaning,omitempty"`
				Order         *int    `json:"order,omitempty"`
			} `json:"AR,omitempty"`
			AU *[]struct {
				Certification *string `json:"certification,omitempty"`
				Meaning       *string `json:"meaning,omitempty"`
				Order         *int    `json:"order,omitempty"`
			} `json:"AU,omitempty"`
			BG *[]struct {
				Certification *string `json:"certification,omitempty"`
				Meaning       *string `json:"meaning,omitempty"`
				Order         *int    `json:"order,omitempty"`
			} `json:"BG,omitempty"`
			BR *[]struct {
				Certification *string `json:"certification,omitempty"`
				Meaning       *string `json:"meaning,omitempty"`
				Order         *int    `json:"order,omitempty"`
			} `json:"BR,omitempty"`
			CA *[]struct {
				Certification *string `json:"certification,omitempty"`
				Meaning       *string `json:"meaning,omitempty"`
				Order         *int    `json:"order,omitempty"`
			} `json:"CA,omitempty"`
			CAQC *[]struct {
				Certification *string `json:"certification,omitempty"`
				Meaning       *string `json:"meaning,omitempty"`
				Order         *int    `json:"order,omitempty"`
			} `json:"CA-QC,omitempty"`
			DE *[]struct {
				Certification *string `json:"certification,omitempty"`
				Meaning       *string `json:"meaning,omitempty"`
				Order         *int    `json:"order,omitempty"`
			} `json:"DE,omitempty"`
			DK *[]struct {
				Certification *string `json:"certification,omitempty"`
				Meaning       *string `json:"meaning,omitempty"`
				Order         *int    `json:"order,omitempty"`
			} `json:"DK,omitempty"`
			ES *[]struct {
				Certification *string `json:"certification,omitempty"`
				Meaning       *string `json:"meaning,omitempty"`
				Order         *int    `json:"order,omitempty"`
			} `json:"ES,omitempty"`
			FI *[]struct {
				Certification *string `json:"certification,omitempty"`
				Meaning       *string `json:"meaning,omitempty"`
				Order         *int    `json:"order,omitempty"`
			} `json:"FI,omitempty"`
			FR *[]struct {
				Certification *string `json:"certification,omitempty"`
				Meaning       *string `json:"meaning,omitempty"`
				Order         *int    `json:"order,omitempty"`
			} `json:"FR,omitempty"`
			GB *[]struct {
				Certification *string `json:"certification,omitempty"`
				Meaning       *string `json:"meaning,omitempty"`
				Order         *int    `json:"order,omitempty"`
			} `json:"GB,omitempty"`
			GR *[]struct {
				Certification *string `json:"certification,omitempty"`
				Meaning       *string `json:"meaning,omitempty"`
				Order         *int    `json:"order,omitempty"`
			} `json:"GR,omitempty"`
			HU *[]struct {
				Certification *string `json:"certification,omitempty"`
				Meaning       *string `json:"meaning,omitempty"`
				Order         *int    `json:"order,omitempty"`
			} `json:"HU,omitempty"`
			ID *[]struct {
				Certification *string `json:"certification,omitempty"`
				Meaning       *string `json:"meaning,omitempty"`
				Order         *int    `json:"order,omitempty"`
			} `json:"ID,omitempty"`
			IL *[]struct {
				Certification *string `json:"certification,omitempty"`
				Meaning       *string `json:"meaning,omitempty"`
				Order         *int    `json:"order,omitempty"`
			} `json:"IL,omitempty"`
			IN *[]struct {
				Certification *string `json:"certification,omitempty"`
				Meaning       *string `json:"meaning,omitempty"`
				Order         *int    `json:"order,omitempty"`
			} `json:"IN,omitempty"`
			IT *[]struct {
				Certification *string `json:"certification,omitempty"`
				Meaning       *string `json:"meaning,omitempty"`
				Order         *int    `json:"order,omitempty"`
			} `json:"IT,omitempty"`
			KR *[]struct {
				Certification *string `json:"certification,omitempty"`
				Meaning       *string `json:"meaning,omitempty"`
				Order         *int    `json:"order,omitempty"`
			} `json:"KR,omitempty"`
			LT *[]struct {
				Certification *string `json:"certification,omitempty"`
				Meaning       *string `json:"meaning,omitempty"`
				Order         *int    `json:"order,omitempty"`
			} `json:"LT,omitempty"`
			MA *[]struct {
				Certification *string `json:"certification,omitempty"`
				Meaning       *string `json:"meaning,omitempty"`
				Order         *int    `json:"order,omitempty"`
			} `json:"MA,omitempty"`
			MX *[]struct {
				Certification *string `json:"certification,omitempty"`
				Meaning       *string `json:"meaning,omitempty"`
				Order         *int    `json:"order,omitempty"`
			} `json:"MX,omitempty"`
			MY *[]struct {
				Certification *string `json:"certification,omitempty"`
				Meaning       *string `json:"meaning,omitempty"`
				Order         *int    `json:"order,omitempty"`
			} `json:"MY,omitempty"`
			NL *[]struct {
				Certification *string `json:"certification,omitempty"`
				Meaning       *string `json:"meaning,omitempty"`
				Order         *int    `json:"order,omitempty"`
			} `json:"NL,omitempty"`
			NO *[]struct {
				Certification *string `json:"certification,omitempty"`
				Meaning       *string `json:"meaning,omitempty"`
				Order         *int    `json:"order,omitempty"`
			} `json:"NO,omitempty"`
			NZ *[]struct {
				Certification *string `json:"certification,omitempty"`
				Meaning       *string `json:"meaning,omitempty"`
				Order         *int    `json:"order,omitempty"`
			} `json:"NZ,omitempty"`
			PH *[]struct {
				Certification *string `json:"certification,omitempty"`
				Meaning       *string `json:"meaning,omitempty"`
				Order         *int    `json:"order,omitempty"`
			} `json:"PH,omitempty"`
			PL *[]struct {
				Certification *string `json:"certification,omitempty"`
				Meaning       *string `json:"meaning,omitempty"`
				Order         *int    `json:"order,omitempty"`
			} `json:"PL,omitempty"`
			PR *[]struct {
				Certification *string `json:"certification,omitempty"`
				Meaning       *string `json:"meaning,omitempty"`
				Order         *int    `json:"order,omitempty"`
			} `json:"PR,omitempty"`
			PT *[]struct {
				Certification *string `json:"certification,omitempty"`
				Meaning       *string `json:"meaning,omitempty"`
				Order         *int    `json:"order,omitempty"`
			} `json:"PT,omitempty"`
			RU *[]struct {
				Certification *string `json:"certification,omitempty"`
				Meaning       *string `json:"meaning,omitempty"`
				Order         *int    `json:"order,omitempty"`
			} `json:"RU,omitempty"`
			SE *[]struct {
				Certification *string `json:"certification,omitempty"`
				Meaning       *string `json:"meaning,omitempty"`
				Order         *int    `json:"order,omitempty"`
			} `json:"SE,omitempty"`
			SG *[]struct {
				Certification *string `json:"certification,omitempty"`
				Meaning       *string `json:"meaning,omitempty"`
				Order         *int    `json:"order,omitempty"`
			} `json:"SG,omitempty"`
			SK *[]struct {
				Certification *string `json:"certification,omitempty"`
				Meaning       *string `json:"meaning,omitempty"`
				Order         *int    `json:"order,omitempty"`
			} `json:"SK,omitempty"`
			TH *[]struct {
				Certification *string `json:"certification,omitempty"`
				Meaning       *string `json:"meaning,omitempty"`
				Order         *int    `json:"order,omitempty"`
			} `json:"TH,omitempty"`
			TR *[]struct {
				Certification *string `json:"certification,omitempty"`
				Meaning       *string `json:"meaning,omitempty"`
				Order         *int    `json:"order,omitempty"`
			} `json:"TR,omitempty"`
			TW *[]struct {
				Certification *string `json:"certification,omitempty"`
				Meaning       *string `json:"meaning,omitempty"`
				Order         *int    `json:"order,omitempty"`
			} `json:"TW,omitempty"`
			US *[]struct {
				Certification *string `json:"certification,omitempty"`
				Meaning       *string `json:"meaning,omitempty"`
				Order         *int    `json:"order,omitempty"`
			} `json:"US,omitempty"`
			VI *[]struct {
				Certification *string `json:"certification,omitempty"`
				Meaning       *string `json:"meaning,omitempty"`
				Order         *int    `json:"order,omitempty"`
			} `json:"VI,omitempty"`
			ZA *[]struct {
				Certification *string `json:"certification,omitempty"`
				Meaning       *string `json:"meaning,omitempty"`
				Order         *int    `json:"order,omitempty"`
			} `json:"ZA,omitempty"`
		} `json:"certifications,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r CertificationsTvListResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CertificationsTvListResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r CertificationsTvListResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// MovieListWithResponse request returning *MovieListResponse
func (c *ClientWithResponses) MovieListWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*MovieListResponse, error) {
	rsp, err := c.MovieList(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseMovieListResponse(rsp)
}

// CertificationsTvListWithResponse request returning *CertificationsTvListResponse
func (c *ClientWithResponses) CertificationsTvListWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*CertificationsTvListResponse, error) {
	rsp, err := c.CertificationsTvList(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCertificationsTvListResponse(rsp)
}

// ParseMovieListResponse parses an HTTP response from a MovieListWithResponse call
func ParseMovieListResponse(rsp *http.Response) (*MovieListResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &MovieListResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Certifications *struct {
				AR *[]struct {
					Certification *string `json:"certification,omitempty"`
					Meaning       *string `json:"meaning,omitempty"`
					Order         *int    `json:"order,omitempty"`
				} `json:"AR,omitempty"`
				AU *[]struct {
					Certification *string `json:"certification,omitempty"`
					Meaning       *string `json:"meaning,omitempty"`
					Order         *int    `json:"order,omitempty"`
				} `json:"AU,omitempty"`
				BG *[]struct {
					Certification *string `json:"certification,omitempty"`
					Meaning       *string `json:"meaning,omitempty"`
					Order         *int    `json:"order,omitempty"`
				} `json:"BG,omitempty"`
				BR *[]struct {
					Certification *string `json:"certification,omitempty"`
					Meaning       *string `json:"meaning,omitempty"`
					Order         *int    `json:"order,omitempty"`
				} `json:"BR,omitempty"`
				CA *[]struct {
					Certification *string `json:"certification,omitempty"`
					Meaning       *string `json:"meaning,omitempty"`
					Order         *int    `json:"order,omitempty"`
				} `json:"CA,omitempty"`
				CAQC *[]struct {
					Certification *string `json:"certification,omitempty"`
					Meaning       *string `json:"meaning,omitempty"`
					Order         *int    `json:"order,omitempty"`
				} `json:"CA-QC,omitempty"`
				CH *[]struct {
					Certification *string `json:"certification,omitempty"`
					Meaning       *string `json:"meaning,omitempty"`
					Order         *int    `json:"order,omitempty"`
				} `json:"CH,omitempty"`
				DE *[]struct {
					Certification *string `json:"certification,omitempty"`
					Meaning       *string `json:"meaning,omitempty"`
					Order         *int    `json:"order,omitempty"`
				} `json:"DE,omitempty"`
				DK *[]struct {
					Certification *string `json:"certification,omitempty"`
					Meaning       *string `json:"meaning,omitempty"`
					Order         *int    `json:"order,omitempty"`
				} `json:"DK,omitempty"`
				ES *[]struct {
					Certification *string `json:"certification,omitempty"`
					Meaning       *string `json:"meaning,omitempty"`
					Order         *int    `json:"order,omitempty"`
				} `json:"ES,omitempty"`
				FI *[]struct {
					Certification *string `json:"certification,omitempty"`
					Meaning       *string `json:"meaning,omitempty"`
					Order         *int    `json:"order,omitempty"`
				} `json:"FI,omitempty"`
				FR *[]struct {
					Certification *string `json:"certification,omitempty"`
					Meaning       *string `json:"meaning,omitempty"`
					Order         *int    `json:"order,omitempty"`
				} `json:"FR,omitempty"`
				GB *[]struct {
					Certification *string `json:"certification,omitempty"`
					Meaning       *string `json:"meaning,omitempty"`
					Order         *int    `json:"order,omitempty"`
				} `json:"GB,omitempty"`
				GR *[]struct {
					Certification *string `json:"certification,omitempty"`
					Meaning       *string `json:"meaning,omitempty"`
					Order         *int    `json:"order,omitempty"`
				} `json:"GR,omitempty"`
				HK *[]struct {
					Certification *string `json:"certification,omitempty"`
					Meaning       *string `json:"meaning,omitempty"`
					Order         *int    `json:"order,omitempty"`
				} `json:"HK,omitempty"`
				HU *[]struct {
					Certification *string `json:"certification,omitempty"`
					Meaning       *string `json:"meaning,omitempty"`
					Order         *int    `json:"order,omitempty"`
				} `json:"HU,omitempty"`
				ID *[]struct {
					Certification *string `json:"certification,omitempty"`
					Meaning       *string `json:"meaning,omitempty"`
					Order         *int    `json:"order,omitempty"`
				} `json:"ID,omitempty"`
				IE *[]struct {
					Certification *string `json:"certification,omitempty"`
					Meaning       *string `json:"meaning,omitempty"`
					Order         *int    `json:"order,omitempty"`
				} `json:"IE,omitempty"`
				IL *[]struct {
					Certification *string `json:"certification,omitempty"`
					Meaning       *string `json:"meaning,omitempty"`
					Order         *int    `json:"order,omitempty"`
				} `json:"IL,omitempty"`
				IN *[]struct {
					Certification *string `json:"certification,omitempty"`
					Meaning       *string `json:"meaning,omitempty"`
					Order         *int    `json:"order,omitempty"`
				} `json:"IN,omitempty"`
				IT *[]struct {
					Certification *string `json:"certification,omitempty"`
					Meaning       *string `json:"meaning,omitempty"`
					Order         *int    `json:"order,omitempty"`
				} `json:"IT,omitempty"`
				JP *[]struct {
					Certification *string `json:"certification,omitempty"`
					Meaning       *string `json:"meaning,omitempty"`
					Order         *int    `json:"order,omitempty"`
				} `json:"JP,omitempty"`
				KR *[]struct {
					Certification *string `json:"certification,omitempty"`
					Meaning       *string `json:"meaning,omitempty"`
					Order         *int    `json:"order,omitempty"`
				} `json:"KR,omitempty"`
				LT *[]struct {
					Certification *string `json:"certification,omitempty"`
					Meaning       *string `json:"meaning,omitempty"`
					Order         *int    `json:"order,omitempty"`
				} `json:"LT,omitempty"`
				LU *[]struct {
					Certification *string `json:"certification,omitempty"`
					Meaning       *string `json:"meaning,omitempty"`
					Order         *int    `json:"order,omitempty"`
				} `json:"LU,omitempty"`
				LV *[]struct {
					Certification *string `json:"certification,omitempty"`
					Meaning       *string `json:"meaning,omitempty"`
					Order         *int    `json:"order,omitempty"`
				} `json:"LV,omitempty"`
				MO *[]struct {
					Certification *string `json:"certification,omitempty"`
					Meaning       *string `json:"meaning,omitempty"`
					Order         *int    `json:"order,omitempty"`
				} `json:"MO,omitempty"`
				MX *[]struct {
					Certification *string `json:"certification,omitempty"`
					Meaning       *string `json:"meaning,omitempty"`
					Order         *int    `json:"order,omitempty"`
				} `json:"MX,omitempty"`
				MY *[]struct {
					Certification *string `json:"certification,omitempty"`
					Meaning       *string `json:"meaning,omitempty"`
					Order         *int    `json:"order,omitempty"`
				} `json:"MY,omitempty"`
				NL *[]struct {
					Certification *string `json:"certification,omitempty"`
					Meaning       *string `json:"meaning,omitempty"`
					Order         *int    `json:"order,omitempty"`
				} `json:"NL,omitempty"`
				NO *[]struct {
					Certification *string `json:"certification,omitempty"`
					Meaning       *string `json:"meaning,omitempty"`
					Order         *int    `json:"order,omitempty"`
				} `json:"NO,omitempty"`
				NZ *[]struct {
					Certification *string `json:"certification,omitempty"`
					Meaning       *string `json:"meaning,omitempty"`
					Order         *int    `json:"order,omitempty"`
				} `json:"NZ,omitempty"`
				PH *[]struct {
					Certification *string `json:"certification,omitempty"`
					Meaning       *string `json:"meaning,omitempty"`
					Order         *int    `json:"order,omitempty"`
				} `json:"PH,omitempty"`
				PR *[]struct {
					Certification *string `json:"certification,omitempty"`
					Meaning       *string `json:"meaning,omitempty"`
					Order         *int    `json:"order,omitempty"`
				} `json:"PR,omitempty"`
				PT *[]struct {
					Certification *string `json:"certification,omitempty"`
					Meaning       *string `json:"meaning,omitempty"`
					Order         *int    `json:"order,omitempty"`
				} `json:"PT,omitempty"`
				RU *[]struct {
					Certification *string `json:"certification,omitempty"`
					Meaning       *string `json:"meaning,omitempty"`
					Order         *int    `json:"order,omitempty"`
				} `json:"RU,omitempty"`
				SE *[]struct {
					Certification *string `json:"certification,omitempty"`
					Meaning       *string `json:"meaning,omitempty"`
					Order         *int    `json:"order,omitempty"`
				} `json:"SE,omitempty"`
				SG *[]struct {
					Certification *string `json:"certification,omitempty"`
					Meaning       *string `json:"meaning,omitempty"`
					Order         *int    `json:"order,omitempty"`
				} `json:"SG,omitempty"`
				SK *[]struct {
					Certification *string `json:"certification,omitempty"`
					Meaning       *string `json:"meaning,omitempty"`
					Order         *int    `json:"order,omitempty"`
				} `json:"SK,omitempty"`
				TH *[]struct {
					Certification *string `json:"certification,omitempty"`
					Meaning       *string `json:"meaning,omitempty"`
					Order         *int    `json:"order,omitempty"`
				} `json:"TH,omitempty"`
				TR *[]struct {
					Certification *string `json:"certification,omitempty"`
					Meaning       *string `json:"meaning,omitempty"`
					Order         *int    `json:"order,omitempty"`
				} `json:"TR,omitempty"`
				TW *[]struct {
					Certification *string `json:"certification,omitempty"`
					Meaning       *string `json:"meaning,omitempty"`
					Order         *int    `json:"order,omitempty"`
				} `json:"TW,omitempty"`
				US *[]struct {
					Certification *string `json:"certification,omitempty"`
					Meaning       *string `json:"meaning,omitempty"`
					Order         *int    `json:"order,omitempty"`
				} `json:"US,omitempty"`
				VI *[]struct {
					Certification *string `json:"certification,omitempty"`
					Meaning       *string `json:"meaning,omitempty"`
					Order         *int    `json:"order,omitempty"`
				} `json:"VI,omitempty"`
				ZA *[]struct {
					Certification *string `json:"certification,omitempty"`
					Meaning       *string `json:"meaning,omitempty"`
					Order         *int    `json:"order,omitempty"`
				} `json:"ZA,omitempty"`
			} `json:"certifications,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseCertificationsTvListResponse parses an HTTP response from a CertificationsTvListWithResponse call
func ParseCertificationsTvListResponse(rsp *http.Response) (*CertificationsTvListResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CertificationsTvListResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Certifications *struct {
				AR *[]struct {
					Certification *string `json:"certification,omitempty"`
					Meaning       *string `json:"meaning,omitempty"`
					Order         *int    `json:"order,omitempty"`
				} `json:"AR,omitempty"`
				AU *[]struct {
					Certification *string `json:"certification,omitempty"`
					Meaning       *string `json:"meaning,omitempty"`
					Order         *int    `json:"order,omitempty"`
				} `json:"AU,omitempty"`
				BG *[]struct {
					Certification *string `json:"certification,omitempty"`
					Meaning       *string `json:"meaning,omitempty"`
					Order         *int    `json:"order,omitempty"`
				} `json:"BG,omitempty"`
				BR *[]struct {
					Certification *string `json:"certification,omitempty"`
					Meaning       *string `json:"meaning,omitempty"`
					Order         *int    `json:"order,omitempty"`
				} `json:"BR,omitempty"`
				CA *[]struct {
					Certification *string `json:"certification,omitempty"`
					Meaning       *string `json:"meaning,omitempty"`
					Order         *int    `json:"order,omitempty"`
				} `json:"CA,omitempty"`
				CAQC *[]struct {
					Certification *string `json:"certification,omitempty"`
					Meaning       *string `json:"meaning,omitempty"`
					Order         *int    `json:"order,omitempty"`
				} `json:"CA-QC,omitempty"`
				DE *[]struct {
					Certification *string `json:"certification,omitempty"`
					Meaning       *string `json:"meaning,omitempty"`
					Order         *int    `json:"order,omitempty"`
				} `json:"DE,omitempty"`
				DK *[]struct {
					Certification *string `json:"certification,omitempty"`
					Meaning       *string `json:"meaning,omitempty"`
					Order         *int    `json:"order,omitempty"`
				} `json:"DK,omitempty"`
				ES *[]struct {
					Certification *string `json:"certification,omitempty"`
					Meaning       *string `json:"meaning,omitempty"`
					Order         *int    `json:"order,omitempty"`
				} `json:"ES,omitempty"`
				FI *[]struct {
					Certification *string `json:"certification,omitempty"`
					Meaning       *string `json:"meaning,omitempty"`
					Order         *int    `json:"order,omitempty"`
				} `json:"FI,omitempty"`
				FR *[]struct {
					Certification *string `json:"certification,omitempty"`
					Meaning       *string `json:"meaning,omitempty"`
					Order         *int    `json:"order,omitempty"`
				} `json:"FR,omitempty"`
				GB *[]struct {
					Certification *string `json:"certification,omitempty"`
					Meaning       *string `json:"meaning,omitempty"`
					Order         *int    `json:"order,omitempty"`
				} `json:"GB,omitempty"`
				GR *[]struct {
					Certification *string `json:"certification,omitempty"`
					Meaning       *string `json:"meaning,omitempty"`
					Order         *int    `json:"order,omitempty"`
				} `json:"GR,omitempty"`
				HU *[]struct {
					Certification *string `json:"certification,omitempty"`
					Meaning       *string `json:"meaning,omitempty"`
					Order         *int    `json:"order,omitempty"`
				} `json:"HU,omitempty"`
				ID *[]struct {
					Certification *string `json:"certification,omitempty"`
					Meaning       *string `json:"meaning,omitempty"`
					Order         *int    `json:"order,omitempty"`
				} `json:"ID,omitempty"`
				IL *[]struct {
					Certification *string `json:"certification,omitempty"`
					Meaning       *string `json:"meaning,omitempty"`
					Order         *int    `json:"order,omitempty"`
				} `json:"IL,omitempty"`
				IN *[]struct {
					Certification *string `json:"certification,omitempty"`
					Meaning       *string `json:"meaning,omitempty"`
					Order         *int    `json:"order,omitempty"`
				} `json:"IN,omitempty"`
				IT *[]struct {
					Certification *string `json:"certification,omitempty"`
					Meaning       *string `json:"meaning,omitempty"`
					Order         *int    `json:"order,omitempty"`
				} `json:"IT,omitempty"`
				KR *[]struct {
					Certification *string `json:"certification,omitempty"`
					Meaning       *string `json:"meaning,omitempty"`
					Order         *int    `json:"order,omitempty"`
				} `json:"KR,omitempty"`
				LT *[]struct {
					Certification *string `json:"certification,omitempty"`
					Meaning       *string `json:"meaning,omitempty"`
					Order         *int    `json:"order,omitempty"`
				} `json:"LT,omitempty"`
				MA *[]struct {
					Certification *string `json:"certification,omitempty"`
					Meaning       *string `json:"meaning,omitempty"`
					Order         *int    `json:"order,omitempty"`
				} `json:"MA,omitempty"`
				MX *[]struct {
					Certification *string `json:"certification,omitempty"`
					Meaning       *string `json:"meaning,omitempty"`
					Order         *int    `json:"order,omitempty"`
				} `json:"MX,omitempty"`
				MY *[]struct {
					Certification *string `json:"certification,omitempty"`
					Meaning       *string `json:"meaning,omitempty"`
					Order         *int    `json:"order,omitempty"`
				} `json:"MY,omitempty"`
				NL *[]struct {
					Certification *string `json:"certification,omitempty"`
					Meaning       *string `json:"meaning,omitempty"`
					Order         *int    `json:"order,omitempty"`
				} `json:"NL,omitempty"`
				NO *[]struct {
					Certification *string `json:"certification,omitempty"`
					Meaning       *string `json:"meaning,omitempty"`
					Order         *int    `json:"order,omitempty"`
				} `json:"NO,omitempty"`
				NZ *[]struct {
					Certification *string `json:"certification,omitempty"`
					Meaning       *string `json:"meaning,omitempty"`
					Order         *int    `json:"order,omitempty"`
				} `json:"NZ,omitempty"`
				PH *[]struct {
					Certification *string `json:"certification,omitempty"`
					Meaning       *string `json:"meaning,omitempty"`
					Order         *int    `json:"order,omitempty"`
				} `json:"PH,omitempty"`
				PL *[]struct {
					Certification *string `json:"certification,omitempty"`
					Meaning       *string `json:"meaning,omitempty"`
					Order         *int    `json:"order,omitempty"`
				} `json:"PL,omitempty"`
				PR *[]struct {
					Certification *string `json:"certification,omitempty"`
					Meaning       *string `json:"meaning,omitempty"`
					Order         *int    `json:"order,omitempty"`
				} `json:"PR,omitempty"`
				PT *[]struct {
					Certification *string `json:"certification,omitempty"`
					Meaning       *string `json:"meaning,omitempty"`
					Order         *int    `json:"order,omitempty"`
				} `json:"PT,omitempty"`
				RU *[]struct {
					Certification *string `json:"certification,omitempty"`
					Meaning       *string `json:"meaning,omitempty"`
					Order         *int    `json:"order,omitempty"`
				} `json:"RU,omitempty"`
				SE *[]struct {
					Certification *string `json:"certification,omitempty"`
					Meaning       *string `json:"meaning,omitempty"`
					Order         *int    `json:"order,omitempty"`
				} `json:"SE,omitempty"`
				SG *[]struct {
					Certification *string `json:"certification,omitempty"`
					Meaning       *string `json:"meaning,omitempty"`
					Order         *int    `json:"order,omitempty"`
				} `json:"SG,omitempty"`
				SK *[]struct {
					Certification *string `json:"certification,omitempty"`
					Meaning       *string `json:"meaning,omitempty"`
					Order         *int    `json:"order,omitempty"`
				} `json:"SK,omitempty"`
				TH *[]struct {
					Certification *string `json:"certification,omitempty"`
					Meaning       *string `json:"meaning,omitempty"`
					Order         *int    `json:"order,omitempty"`
				} `json:"TH,omitempty"`
				TR *[]struct {
					Certification *string `json:"certification,omitempty"`
					Meaning       *string `json:"meaning,omitempty"`
					Order         *int    `json:"order,omitempty"`
				} `json:"TR,omitempty"`
				TW *[]struct {
					Certification *string `json:"certification,omitempty"`
					Meaning       *string `json:"meaning,omitempty"`
					Order         *int    `json:"order,omitempty"`
				} `json:"TW,omitempty"`
				US *[]struct {
					Certification *string `json:"certification,omitempty"`
					Meaning       *string `json:"meaning,omitempty"`
					Order         *int    `json:"order,omitempty"`
				} `json:"US,omitempty"`
				VI *[]struct {
					Certification *string `json:"certification,omitempty"`
					Meaning       *string `json:"meaning,omitempty"`
					Order         *int    `json:"order,omitempty"`
				} `json:"VI,omitempty"`
				ZA *[]struct {
					Certification *string `json:"certification,omitempty"`
					Meaning       *string `json:"meaning,omitempty"`
					Order         *int    `json:"order,omitempty"`
				} `json:"ZA,omitempty"`
			} `json:"certifications,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}
