// Package trending provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package trending

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
)

const (
	Sec0Scopes sec0ContextKey = "sec0.Scopes"
)

// Defines values for AllParamsTimeWindow.
const (
	AllParamsTimeWindowDay  AllParamsTimeWindow = "day"
	AllParamsTimeWindowWeek AllParamsTimeWindow = "week"
)

// Valid indicates whether the value is a known member of the AllParamsTimeWindow enum.
func (e AllParamsTimeWindow) Valid() bool {
	switch e {
	case AllParamsTimeWindowDay:
		return true
	case AllParamsTimeWindowWeek:
		return true
	default:
		return false
	}
}

// Defines values for MoviesParamsTimeWindow.
const (
	MoviesParamsTimeWindowDay  MoviesParamsTimeWindow = "day"
	MoviesParamsTimeWindowWeek MoviesParamsTimeWindow = "week"
)

// Valid indicates whether the value is a known member of the MoviesParamsTimeWindow enum.
func (e MoviesParamsTimeWindow) Valid() bool {
	switch e {
	case MoviesParamsTimeWindowDay:
		return true
	case MoviesParamsTimeWindowWeek:
		return true
	default:
		return false
	}
}

// Defines values for PeopleParamsTimeWindow.
const (
	PeopleParamsTimeWindowDay  PeopleParamsTimeWindow = "day"
	PeopleParamsTimeWindowWeek PeopleParamsTimeWindow = "week"
)

// Valid indicates whether the value is a known member of the PeopleParamsTimeWindow enum.
func (e PeopleParamsTimeWindow) Valid() bool {
	switch e {
	case PeopleParamsTimeWindowDay:
		return true
	case PeopleParamsTimeWindowWeek:
		return true
	default:
		return false
	}
}

// Defines values for TvParamsTimeWindow.
const (
	TvParamsTimeWindowDay  TvParamsTimeWindow = "day"
	TvParamsTimeWindowWeek TvParamsTimeWindow = "week"
)

// Valid indicates whether the value is a known member of the TvParamsTimeWindow enum.
func (e TvParamsTimeWindow) Valid() bool {
	switch e {
	case TvParamsTimeWindowDay:
		return true
	case TvParamsTimeWindowWeek:
		return true
	default:
		return false
	}
}

// sec0ContextKey is the context key for sec0 security scheme
type sec0ContextKey string

// AllParams defines parameters for All.
type AllParams struct {
	// Language `ISO-639-1`-`ISO-3166-1` code
	Language *string `form:"language,omitempty" json:"language,omitempty"`
}

// AllParamsTimeWindow defines parameters for All.
type AllParamsTimeWindow string

// MoviesParams defines parameters for Movies.
type MoviesParams struct {
	// Language `ISO-639-1`-`ISO-3166-1` code
	Language *string `form:"language,omitempty" json:"language,omitempty"`
}

// MoviesParamsTimeWindow defines parameters for Movies.
type MoviesParamsTimeWindow string

// PeopleParams defines parameters for People.
type PeopleParams struct {
	// Language `ISO-639-1`-`ISO-3166-1` code
	Language *string `form:"language,omitempty" json:"language,omitempty"`
}

// PeopleParamsTimeWindow defines parameters for People.
type PeopleParamsTimeWindow string

// TvParams defines parameters for Tv.
type TvParams struct {
	// Language `ISO-639-1`-`ISO-3166-1` code
	Language *string `form:"language,omitempty" json:"language,omitempty"`
}

// TvParamsTimeWindow defines parameters for Tv.
type TvParamsTimeWindow string

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// All request
	All(ctx context.Context, timeWindow AllParamsTimeWindow, params *AllParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// Movies request
	Movies(ctx context.Context, timeWindow MoviesParamsTimeWindow, params *MoviesParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// People request
	People(ctx context.Context, timeWindow PeopleParamsTimeWindow, params *PeopleParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// Tv request
	Tv(ctx context.Context, timeWindow TvParamsTimeWindow, params *TvParams, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) All(ctx context.Context, timeWindow AllParamsTimeWindow, params *AllParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAllRequest(c.Server, timeWindow, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) Movies(ctx context.Context, timeWindow MoviesParamsTimeWindow, params *MoviesParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewMoviesRequest(c.Server, timeWindow, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) People(ctx context.Context, timeWindow PeopleParamsTimeWindow, params *PeopleParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPeopleRequest(c.Server, timeWindow, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) Tv(ctx context.Context, timeWindow TvParamsTimeWindow, params *TvParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewTvRequest(c.Server, timeWindow, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewAllRequest generates requests for All
func NewAllRequest(server string, timeWindow AllParamsTimeWindow, params *AllParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "time_window", timeWindow, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/3/trending/all/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.Language != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "language", *params.Language, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewMoviesRequest generates requests for Movies
func NewMoviesRequest(server string, timeWindow MoviesParamsTimeWindow, params *MoviesParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "time_window", timeWindow, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/3/trending/movie/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.Language != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "language", *params.Language, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPeopleRequest generates requests for People
func NewPeopleRequest(server string, timeWindow PeopleParamsTimeWindow, params *PeopleParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "time_window", timeWindow, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/3/trending/person/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.Language != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "language", *params.Language, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewTvRequest generates requests for Tv
func NewTvRequest(server string, timeWindow TvParamsTimeWindow, params *TvParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "time_window", timeWindow, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/3/trending/tv/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.Language != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "language", *params.Language, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// AllWithResponse request
	AllWithResponse(ctx context.Context, timeWindow AllParamsTimeWindow, params *AllParams, reqEditors ...RequestEditorFn) (*AllResponse, error)

	// MoviesWithResponse request
	MoviesWithResponse(ctx context.Context, timeWindow MoviesParamsTimeWindow, params *MoviesParams, reqEditors ...RequestEditorFn) (*MoviesResponse, error)

	// PeopleWithResponse request
	PeopleWithResponse(ctx context.Context, timeWindow PeopleParamsTimeWindow, params *PeopleParams, reqEditors ...RequestEditorFn) (*PeopleResponse, error)

	// TvWithResponse request
	TvWithResponse(ctx context.Context, timeWindow TvParamsTimeWindow, params *TvParams, reqEditors ...RequestEditorFn) (*TvResponse, error)
}

type AllResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Page    *int `json:"page,omitempty"`
		Results *[]struct {
			Adult            *bool    `json:"adult,omitempty"`
			BackdropPath     *string  `json:"backdrop_path,omitempty"`
			GenreIds         *[]int   `json:"genre_ids,omitempty"`
			Id               *int     `json:"id,omitempty"`
			MediaType        *string  `json:"media_type,omitempty"`
			OriginalLanguage *string  `json:"original_language,omitempty"`
			OriginalTitle    *string  `json:"original_title,omitempty"`
			Overview         *string  `json:"overview,omitempty"`
			Popularity       *float32 `json:"popularity,omitempty"`
			PosterPath       *string  `json:"poster_path,omitempty"`
			ReleaseDate      *string  `json:"release_date,omitempty"`
			Title            *string  `json:"title,omitempty"`
			Video            *bool    `json:"video,omitempty"`
			VoteAverage      *float32 `json:"vote_average,omitempty"`
			VoteCount        *int     `json:"vote_count,omitempty"`
		} `json:"results,omitempty"`
		TotalPages   *int `json:"total_pages,omitempty"`
		TotalResults *int `json:"total_results,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r AllResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r AllResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r AllResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type MoviesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Page    *int `json:"page,omitempty"`
		Results *[]struct {
			Adult            *bool    `json:"adult,omitempty"`
			BackdropPath     *string  `json:"backdrop_path,omitempty"`
			GenreIds         *[]int   `json:"genre_ids,omitempty"`
			Id               *int     `json:"id,omitempty"`
			MediaType        *string  `json:"media_type,omitempty"`
			OriginalLanguage *string  `json:"original_language,omitempty"`
			OriginalTitle    *string  `json:"original_title,omitempty"`
			Overview         *string  `json:"overview,omitempty"`
			Popularity       *float32 `json:"popularity,omitempty"`
			PosterPath       *string  `json:"poster_path,omitempty"`
			ReleaseDate      *string  `json:"release_date,omitempty"`
			Title            *string  `json:"title,omitempty"`
			Video            *bool    `json:"video,omitempty"`
			VoteAverage      *float32 `json:"vote_average,omitempty"`
			VoteCount        *int     `json:"vote_count,omitempty"`
		} `json:"results,omitempty"`
		TotalPages   *int `json:"total_pages,omitempty"`
		TotalResults *int `json:"total_results,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r MoviesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r MoviesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r MoviesResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type PeopleResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Page    *int `json:"page,omitempty"`
		Results *[]struct {
			Adult    *bool `json:"adult,omitempty"`
			Gender   *int  `json:"gender,omitempty"`
			Id       *int  `json:"id,omitempty"`
			KnownFor *[]struct {
				Adult            *bool    `json:"adult,omitempty"`
				BackdropPath     *string  `json:"backdrop_path,omitempty"`
				GenreIds         *[]int   `json:"genre_ids,omitempty"`
				Id               *int     `json:"id,omitempty"`
				MediaType        *string  `json:"media_type,omitempty"`
				OriginalLanguage *string  `json:"original_language,omitempty"`
				OriginalTitle    *string  `json:"original_title,omitempty"`
				Overview         *string  `json:"overview,omitempty"`
				Popularity       *float32 `json:"popularity,omitempty"`
				PosterPath       *string  `json:"poster_path,omitempty"`
				ReleaseDate      *string  `json:"release_date,omitempty"`
				Title            *string  `json:"title,omitempty"`
				Video            *bool    `json:"video,omitempty"`
				VoteAverage      *float32 `json:"vote_average,omitempty"`
				VoteCount        *int     `json:"vote_count,omitempty"`
			} `json:"known_for,omitempty"`
			KnownForDepartment *string  `json:"known_for_department,omitempty"`
			MediaType          *string  `json:"media_type,omitempty"`
			Name               *string  `json:"name,omitempty"`
			OriginalName       *string  `json:"original_name,omitempty"`
			Popularity         *float32 `json:"popularity,omitempty"`
			ProfilePath        *string  `json:"profile_path,omitempty"`
		} `json:"results,omitempty"`
		TotalPages   *int `json:"total_pages,omitempty"`
		TotalResults *int `json:"total_results,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r PeopleResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PeopleResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r PeopleResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type TvResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Page    *int `json:"page,omitempty"`
		Results *[]struct {
			Adult            *bool     `json:"adult,omitempty"`
			BackdropPath     *string   `json:"backdrop_path,omitempty"`
			FirstAirDate     *string   `json:"first_air_date,omitempty"`
			GenreIds         *[]int    `json:"genre_ids,omitempty"`
			Id               *int      `json:"id,omitempty"`
			MediaType        *string   `json:"media_type,omitempty"`
			Name             *string   `json:"name,omitempty"`
			OriginCountry    *[]string `json:"origin_country,omitempty"`
			OriginalLanguage *string   `json:"original_language,omitempty"`
			OriginalName     *string   `json:"original_name,omitempty"`
			Overview         *string   `json:"overview,omitempty"`
			Popularity       *float32  `json:"popularity,omitempty"`
			PosterPath       *string   `json:"poster_path,omitempty"`
			VoteAverage      *float32  `json:"vote_average,omitempty"`
			VoteCount        *int      `json:"vote_count,omitempty"`
		} `json:"results,omitempty"`
		TotalPages   *int `json:"total_pages,omitempty"`
		TotalResults *int `json:"total_results,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r TvResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r TvResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r TvResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// AllWithResponse request returning *AllResponse
func (c *ClientWithResponses) AllWithResponse(ctx context.Context, timeWindow AllParamsTimeWindow, params *AllParams, reqEditors ...RequestEditorFn) (*AllResponse, error) {
	rsp, err := c.All(ctx, timeWindow, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseAllResponse(rsp)
}

// MoviesWithResponse request returning *MoviesResponse
func (c *ClientWithResponses) MoviesWithResponse(ctx context.Context, timeWindow MoviesParamsTimeWindow, params *MoviesParams, reqEditors ...RequestEditorFn) (*MoviesResponse, error) {
	rsp, err := c.Movies(ctx, timeWindow, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseMoviesResponse(rsp)
}

// PeopleWithResponse request returning *PeopleResponse
func (c *ClientWithResponses) PeopleWithResponse(ctx context.Context, timeWindow PeopleParamsTimeWindow, params *PeopleParams, reqEditors ...RequestEditorFn) (*PeopleResponse, error) {
	rsp, err := c.People(ctx, timeWindow, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePeopleResponse(rsp)
}

// TvWithResponse request returning *TvResponse
func (c *ClientWithResponses) TvWithResponse(ctx context.Context, timeWindow TvParamsTimeWindow, params *TvParams, reqEditors ...RequestEditorFn) (*TvResponse, error) {
	rsp, err := c.Tv(ctx, timeWindow, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseTvResponse(rsp)
}

// ParseAllResponse parses an HTTP response from a AllWithResponse call
func ParseAllResponse(rsp *http.Response) (*AllResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &AllResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Page    *int `json:"page,omitempty"`
			Results *[]struct {
				Adult            *bool    `json:"adult,omitempty"`
				BackdropPath     *string  `json:"backdrop_path,omitempty"`
				GenreIds         *[]int   `json:"genre_ids,omitempty"`
				Id               *int     `json:"id,omitempty"`
				MediaType        *string  `json:"media_type,omitempty"`
				OriginalLanguage *string  `json:"original_language,omitempty"`
				OriginalTitle    *string  `json:"original_title,omitempty"`
				Overview         *string  `json:"overview,omitempty"`
				Popularity       *float32 `json:"popularity,omitempty"`
				PosterPath       *string  `json:"poster_path,omitempty"`
				ReleaseDate      *string  `json:"release_date,omitempty"`
				Title            *string  `json:"title,omitempty"`
				Video            *bool    `json:"video,omitempty"`
				VoteAverage      *float32 `json:"vote_average,omitempty"`
				VoteCount        *int     `json:"vote_count,omitempty"`
			} `json:"results,omitempty"`
			TotalPages   *int `json:"total_pages,omitempty"`
			TotalResults *int `json:"total_results,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseMoviesResponse parses an HTTP response from a MoviesWithResponse call
func ParseMoviesResponse(rsp *http.Response) (*MoviesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &MoviesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Page    *int `json:"page,omitempty"`
			Results *[]struct {
				Adult            *bool    `json:"adult,omitempty"`
				BackdropPath     *string  `json:"backdrop_path,omitempty"`
				GenreIds         *[]int   `json:"genre_ids,omitempty"`
				Id               *int     `json:"id,omitempty"`
				MediaType        *string  `json:"media_type,omitempty"`
				OriginalLanguage *string  `json:"original_language,omitempty"`
				OriginalTitle    *string  `json:"original_title,omitempty"`
				Overview         *string  `json:"overview,omitempty"`
				Popularity       *float32 `json:"popularity,omitempty"`
				PosterPath       *string  `json:"poster_path,omitempty"`
				ReleaseDate      *string  `json:"release_date,omitempty"`
				Title            *string  `json:"title,omitempty"`
				Video            *bool    `json:"video,omitempty"`
				VoteAverage      *float32 `json:"vote_average,omitempty"`
				VoteCount        *int     `json:"vote_count,omitempty"`
			} `json:"results,omitempty"`
			TotalPages   *int `json:"total_pages,omitempty"`
			TotalResults *int `json:"total_results,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePeopleResponse parses an HTTP response from a PeopleWithResponse call
func ParsePeopleResponse(rsp *http.Response) (*PeopleResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PeopleResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Page    *int `json:"page,omitempty"`
			Results *[]struct {
				Adult    *bool `json:"adult,omitempty"`
				Gender   *int  `json:"gender,omitempty"`
				Id       *int  `json:"id,omitempty"`
				KnownFor *[]struct {
					Adult            *bool    `json:"adult,omitempty"`
					BackdropPath     *string  `json:"backdrop_path,omitempty"`
					GenreIds         *[]int   `json:"genre_ids,omitempty"`
					Id               *int     `json:"id,omitempty"`
					MediaType        *string  `json:"media_type,omitempty"`
					OriginalLanguage *string  `json:"original_language,omitempty"`
					OriginalTitle    *string  `json:"original_title,omitempty"`
					Overview         *string  `json:"overview,omitempty"`
					Popularity       *float32 `json:"popularity,omitempty"`
					PosterPath       *string  `json:"poster_path,omitempty"`
					ReleaseDate      *string  `json:"release_date,omitempty"`
					Title            *string  `json:"title,omitempty"`
					Video            *bool    `json:"video,omitempty"`
					VoteAverage      *float32 `json:"vote_average,omitempty"`
					VoteCount        *int     `json:"vote_count,omitempty"`
				} `json:"known_for,omitempty"`
				KnownForDepartment *string  `json:"known_for_department,omitempty"`
				MediaType          *string  `json:"media_type,omitempty"`
				Name               *string  `json:"name,omitempty"`
				OriginalName       *string  `json:"original_name,omitempty"`
				Popularity         *float32 `json:"popularity,omitempty"`
				ProfilePath        *string  `json:"profile_path,omitempty"`
			} `json:"results,omitempty"`
			TotalPages   *int `json:"total_pages,omitempty"`
			TotalResults *int `json:"total_results,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseTvResponse parses an HTTP response from a TvWithResponse call
func ParseTvResponse(rsp *http.Response) (*TvResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &TvResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Page    *int `json:"page,omitempty"`
			Results *[]struct {
				Adult            *bool     `json:"adult,omitempty"`
				BackdropPath     *string   `json:"backdrop_path,omitempty"`
				FirstAirDate     *string   `json:"first_air_date,omitempty"`
				GenreIds         *[]int    `json:"genre_ids,omitempty"`
				Id               *int      `json:"id,omitempty"`
				MediaType        *string   `json:"media_type,omitempty"`
				Name             *string   `json:"name,omitempty"`
				OriginCountry    *[]string `json:"origin_country,omitempty"`
				OriginalLanguage *string   `json:"original_language,omitempty"`
				OriginalName     *string   `json:"original_name,omitempty"`
				Overview         *string   `json:"overview,omitempty"`
				Popularity       *float32  `json:"popularity,omitempty"`
				PosterPath       *string   `json:"poster_path,omitempty"`
				VoteAverage      *float32  `json:"vote_average,omitempty"`
				VoteCount        *int      `json:"vote_count,omitempty"`
			} `json:"results,omitempty"`
			TotalPages   *int `json:"total_pages,omitempty"`
			TotalResults *int `json:"total_results,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}
