// Package review provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package review

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
)

const (
	Sec0Scopes sec0ContextKey = "sec0.Scopes"
)

// sec0ContextKey is the context key for sec0 security scheme
type sec0ContextKey string

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// Details request
	Details(ctx context.Context, reviewId string, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) Details(ctx context.Context, reviewId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDetailsRequest(c.Server, reviewId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewDetailsRequest generates requests for Details
func NewDetailsRequest(server string, reviewId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "review_id", reviewId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/3/review/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// DetailsWithResponse request
	DetailsWithResponse(ctx context.Context, reviewId string, reqEditors ...RequestEditorFn) (*DetailsResponse, error)
}

type DetailsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Author        *string `json:"author,omitempty"`
		AuthorDetails *struct {
			AvatarPath *string `json:"avatar_path,omitempty"`
			Name       *string `json:"name,omitempty"`
			Rating     *int    `json:"rating,omitempty"`
			Username   *string `json:"username,omitempty"`
		} `json:"author_details,omitempty"`
		Content    *string `json:"content,omitempty"`
		CreatedAt  *string `json:"created_at,omitempty"`
		Id         *string `json:"id,omitempty"`
		Iso6391    *string `json:"iso_639_1,omitempty"`
		MediaId    *int    `json:"media_id,omitempty"`
		MediaTitle *string `json:"media_title,omitempty"`
		MediaType  *string `json:"media_type,omitempty"`
		UpdatedAt  *string `json:"updated_at,omitempty"`
		Url        *string `json:"url,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r DetailsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DetailsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r DetailsResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// DetailsWithResponse request returning *DetailsResponse
func (c *ClientWithResponses) DetailsWithResponse(ctx context.Context, reviewId string, reqEditors ...RequestEditorFn) (*DetailsResponse, error) {
	rsp, err := c.Details(ctx, reviewId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDetailsResponse(rsp)
}

// ParseDetailsResponse parses an HTTP response from a DetailsWithResponse call
func ParseDetailsResponse(rsp *http.Response) (*DetailsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DetailsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Author        *string `json:"author,omitempty"`
			AuthorDetails *struct {
				AvatarPath *string `json:"avatar_path,omitempty"`
				Name       *string `json:"name,omitempty"`
				Rating     *int    `json:"rating,omitempty"`
				Username   *string `json:"username,omitempty"`
			} `json:"author_details,omitempty"`
			Content    *string `json:"content,omitempty"`
			CreatedAt  *string `json:"created_at,omitempty"`
			Id         *string `json:"id,omitempty"`
			Iso6391    *string `json:"iso_639_1,omitempty"`
			MediaId    *int    `json:"media_id,omitempty"`
			MediaTitle *string `json:"media_title,omitempty"`
			MediaType  *string `json:"media_type,omitempty"`
			UpdatedAt  *string `json:"updated_at,omitempty"`
			Url        *string `json:"url,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}
