// Package account provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package account

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
)

const (
	Sec0Scopes sec0ContextKey = "sec0.Scopes"
)

// Defines values for GetFavoritesParamsSortBy.
const (
	GetFavoritesParamsSortByCreatedAtAsc  GetFavoritesParamsSortBy = "created_at.asc"
	GetFavoritesParamsSortByCreatedAtDesc GetFavoritesParamsSortBy = "created_at.desc"
)

// Valid indicates whether the value is a known member of the GetFavoritesParamsSortBy enum.
func (e GetFavoritesParamsSortBy) Valid() bool {
	switch e {
	case GetFavoritesParamsSortByCreatedAtAsc:
		return true
	case GetFavoritesParamsSortByCreatedAtDesc:
		return true
	default:
		return false
	}
}

// Defines values for FavoriteTvParamsSortBy.
const (
	FavoriteTvParamsSortByCreatedAtAsc  FavoriteTvParamsSortBy = "created_at.asc"
	FavoriteTvParamsSortByCreatedAtDesc FavoriteTvParamsSortBy = "created_at.desc"
)

// Valid indicates whether the value is a known member of the FavoriteTvParamsSortBy enum.
func (e FavoriteTvParamsSortBy) Valid() bool {
	switch e {
	case FavoriteTvParamsSortByCreatedAtAsc:
		return true
	case FavoriteTvParamsSortByCreatedAtDesc:
		return true
	default:
		return false
	}
}

// Defines values for RatedMoviesParamsSortBy.
const (
	RatedMoviesParamsSortByCreatedAtAsc  RatedMoviesParamsSortBy = "created_at.asc"
	RatedMoviesParamsSortByCreatedAtDesc RatedMoviesParamsSortBy = "created_at.desc"
)

// Valid indicates whether the value is a known member of the RatedMoviesParamsSortBy enum.
func (e RatedMoviesParamsSortBy) Valid() bool {
	switch e {
	case RatedMoviesParamsSortByCreatedAtAsc:
		return true
	case RatedMoviesParamsSortByCreatedAtDesc:
		return true
	default:
		return false
	}
}

// Defines values for RatedTvParamsSortBy.
const (
	RatedTvParamsSortByCreatedAtAsc  RatedTvParamsSortBy = "created_at.asc"
	RatedTvParamsSortByCreatedAtDesc RatedTvParamsSortBy = "created_at.desc"
)

// Valid indicates whether the value is a known member of the RatedTvParamsSortBy enum.
func (e RatedTvParamsSortBy) Valid() bool {
	switch e {
	case RatedTvParamsSortByCreatedAtAsc:
		return true
	case RatedTvParamsSortByCreatedAtDesc:
		return true
	default:
		return false
	}
}

// Defines values for RatedTvEpisodesParamsSortBy.
const (
	RatedTvEpisodesParamsSortByCreatedAtAsc  RatedTvEpisodesParamsSortBy = "created_at.asc"
	RatedTvEpisodesParamsSortByCreatedAtDesc RatedTvEpisodesParamsSortBy = "created_at.desc"
)

// Valid indicates whether the value is a known member of the RatedTvEpisodesParamsSortBy enum.
func (e RatedTvEpisodesParamsSortBy) Valid() bool {
	switch e {
	case RatedTvEpisodesParamsSortByCreatedAtAsc:
		return true
	case RatedTvEpisodesParamsSortByCreatedAtDesc:
		return true
	default:
		return false
	}
}

// Defines values for WatchlistMoviesParamsSortBy.
const (
	WatchlistMoviesParamsSortByCreatedAtAsc  WatchlistMoviesParamsSortBy = "created_at.asc"
	WatchlistMoviesParamsSortByCreatedAtDesc WatchlistMoviesParamsSortBy = "created_at.desc"
)

// Valid indicates whether the value is a known member of the WatchlistMoviesParamsSortBy enum.
func (e WatchlistMoviesParamsSortBy) Valid() bool {
	switch e {
	case WatchlistMoviesParamsSortByCreatedAtAsc:
		return true
	case WatchlistMoviesParamsSortByCreatedAtDesc:
		return true
	default:
		return false
	}
}

// Defines values for WatchlistTvParamsSortBy.
const (
	CreatedAtAsc  WatchlistTvParamsSortBy = "created_at.asc"
	CreatedAtDesc WatchlistTvParamsSortBy = "created_at.desc"
)

// Valid indicates whether the value is a known member of the WatchlistTvParamsSortBy enum.
func (e WatchlistTvParamsSortBy) Valid() bool {
	switch e {
	case CreatedAtAsc:
		return true
	case CreatedAtDesc:
		return true
	default:
		return false
	}
}

// sec0ContextKey is the context key for sec0 security scheme
type sec0ContextKey string

// DetailsParams defines parameters for Details.
type DetailsParams struct {
	SessionId *string `form:"session_id,omitempty" json:"session_id,omitempty"`
}

// AddFavoriteJSONBody defines parameters for AddFavorite.
type AddFavoriteJSONBody struct {
	RAWBODY json.RawMessage `json:"RAW_BODY"`
}

// AddFavoriteParams defines parameters for AddFavorite.
type AddFavoriteParams struct {
	SessionId *string `form:"session_id,omitempty" json:"session_id,omitempty"`
}

// GetFavoritesParams defines parameters for GetFavorites.
type GetFavoritesParams struct {
	Language  *string                   `form:"language,omitempty" json:"language,omitempty"`
	Page      *int32                    `form:"page,omitempty" json:"page,omitempty"`
	SessionId *string                   `form:"session_id,omitempty" json:"session_id,omitempty"`
	SortBy    *GetFavoritesParamsSortBy `form:"sort_by,omitempty" json:"sort_by,omitempty"`
}

// GetFavoritesParamsSortBy defines parameters for GetFavorites.
type GetFavoritesParamsSortBy string

// FavoriteTvParams defines parameters for FavoriteTv.
type FavoriteTvParams struct {
	Language  *string                 `form:"language,omitempty" json:"language,omitempty"`
	Page      *int32                  `form:"page,omitempty" json:"page,omitempty"`
	SessionId *string                 `form:"session_id,omitempty" json:"session_id,omitempty"`
	SortBy    *FavoriteTvParamsSortBy `form:"sort_by,omitempty" json:"sort_by,omitempty"`
}

// FavoriteTvParamsSortBy defines parameters for FavoriteTv.
type FavoriteTvParamsSortBy string

// ListsParams defines parameters for Lists.
type ListsParams struct {
	Page      *int32  `form:"page,omitempty" json:"page,omitempty"`
	SessionId *string `form:"session_id,omitempty" json:"session_id,omitempty"`
}

// RatedMoviesParams defines parameters for RatedMovies.
type RatedMoviesParams struct {
	Language  *string                  `form:"language,omitempty" json:"language,omitempty"`
	Page      *int32                   `form:"page,omitempty" json:"page,omitempty"`
	SessionId *string                  `form:"session_id,omitempty" json:"session_id,omitempty"`
	SortBy    *RatedMoviesParamsSortBy `form:"sort_by,omitempty" json:"sort_by,omitempty"`
}

// RatedMoviesParamsSortBy defines parameters for RatedMovies.
type RatedMoviesParamsSortBy string

// RatedTvParams defines parameters for RatedTv.
type RatedTvParams struct {
	Language  *string              `form:"language,omitempty" json:"language,omitempty"`
	Page      *int32               `form:"page,omitempty" json:"page,omitempty"`
	SessionId *string              `form:"session_id,omitempty" json:"session_id,omitempty"`
	SortBy    *RatedTvParamsSortBy `form:"sort_by,omitempty" json:"sort_by,omitempty"`
}

// RatedTvParamsSortBy defines parameters for RatedTv.
type RatedTvParamsSortBy string

// RatedTvEpisodesParams defines parameters for RatedTvEpisodes.
type RatedTvEpisodesParams struct {
	Language  *string                      `form:"language,omitempty" json:"language,omitempty"`
	Page      *int32                       `form:"page,omitempty" json:"page,omitempty"`
	SessionId *string                      `form:"session_id,omitempty" json:"session_id,omitempty"`
	SortBy    *RatedTvEpisodesParamsSortBy `form:"sort_by,omitempty" json:"sort_by,omitempty"`
}

// RatedTvEpisodesParamsSortBy defines parameters for RatedTvEpisodes.
type RatedTvEpisodesParamsSortBy string

// AddToWatchlistJSONBody defines parameters for AddToWatchlist.
type AddToWatchlistJSONBody struct {
	RAWBODY json.RawMessage `json:"RAW_BODY"`
}

// AddToWatchlistParams defines parameters for AddToWatchlist.
type AddToWatchlistParams struct {
	SessionId *string `form:"session_id,omitempty" json:"session_id,omitempty"`
}

// WatchlistMoviesParams defines parameters for WatchlistMovies.
type WatchlistMoviesParams struct {
	Language  *string                      `form:"language,omitempty" json:"language,omitempty"`
	Page      *int32                       `form:"page,omitempty" json:"page,omitempty"`
	SessionId *string                      `form:"session_id,omitempty" json:"session_id,omitempty"`
	SortBy    *WatchlistMoviesParamsSortBy `form:"sort_by,omitempty" json:"sort_by,omitempty"`
}

// WatchlistMoviesParamsSortBy defines parameters for WatchlistMovies.
type WatchlistMoviesParamsSortBy string

// WatchlistTvParams defines parameters for WatchlistTv.
type WatchlistTvParams struct {
	Language  *string                  `form:"language,omitempty" json:"language,omitempty"`
	Page      *int32                   `form:"page,omitempty" json:"page,omitempty"`
	SessionId *string                  `form:"session_id,omitempty" json:"session_id,omitempty"`
	SortBy    *WatchlistTvParamsSortBy `form:"sort_by,omitempty" json:"sort_by,omitempty"`
}

// WatchlistTvParamsSortBy defines parameters for WatchlistTv.
type WatchlistTvParamsSortBy string

// AddFavoriteJSONRequestBody defines body for AddFavorite for application/json ContentType.
type AddFavoriteJSONRequestBody AddFavoriteJSONBody

// AddToWatchlistJSONRequestBody defines body for AddToWatchlist for application/json ContentType.
type AddToWatchlistJSONRequestBody AddToWatchlistJSONBody

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// Details request
	Details(ctx context.Context, accountId int32, params *DetailsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// AddFavoriteWithBody request with any body
	AddFavoriteWithBody(ctx context.Context, accountId int32, params *AddFavoriteParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	AddFavorite(ctx context.Context, accountId int32, params *AddFavoriteParams, body AddFavoriteJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetFavorites request
	GetFavorites(ctx context.Context, accountId int32, params *GetFavoritesParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// FavoriteTv request
	FavoriteTv(ctx context.Context, accountId int32, params *FavoriteTvParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// Lists request
	Lists(ctx context.Context, accountId int32, params *ListsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// RatedMovies request
	RatedMovies(ctx context.Context, accountId int32, params *RatedMoviesParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// RatedTv request
	RatedTv(ctx context.Context, accountId int32, params *RatedTvParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// RatedTvEpisodes request
	RatedTvEpisodes(ctx context.Context, accountId int32, params *RatedTvEpisodesParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// AddToWatchlistWithBody request with any body
	AddToWatchlistWithBody(ctx context.Context, accountId int32, params *AddToWatchlistParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	AddToWatchlist(ctx context.Context, accountId int32, params *AddToWatchlistParams, body AddToWatchlistJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// WatchlistMovies request
	WatchlistMovies(ctx context.Context, accountId int32, params *WatchlistMoviesParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// WatchlistTv request
	WatchlistTv(ctx context.Context, accountId int32, params *WatchlistTvParams, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) Details(ctx context.Context, accountId int32, params *DetailsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDetailsRequest(c.Server, accountId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) AddFavoriteWithBody(ctx context.Context, accountId int32, params *AddFavoriteParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAddFavoriteRequestWithBody(c.Server, accountId, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) AddFavorite(ctx context.Context, accountId int32, params *AddFavoriteParams, body AddFavoriteJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAddFavoriteRequest(c.Server, accountId, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetFavorites(ctx context.Context, accountId int32, params *GetFavoritesParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetFavoritesRequest(c.Server, accountId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) FavoriteTv(ctx context.Context, accountId int32, params *FavoriteTvParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewFavoriteTvRequest(c.Server, accountId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) Lists(ctx context.Context, accountId int32, params *ListsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListsRequest(c.Server, accountId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) RatedMovies(ctx context.Context, accountId int32, params *RatedMoviesParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRatedMoviesRequest(c.Server, accountId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) RatedTv(ctx context.Context, accountId int32, params *RatedTvParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRatedTvRequest(c.Server, accountId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) RatedTvEpisodes(ctx context.Context, accountId int32, params *RatedTvEpisodesParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRatedTvEpisodesRequest(c.Server, accountId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) AddToWatchlistWithBody(ctx context.Context, accountId int32, params *AddToWatchlistParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAddToWatchlistRequestWithBody(c.Server, accountId, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) AddToWatchlist(ctx context.Context, accountId int32, params *AddToWatchlistParams, body AddToWatchlistJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAddToWatchlistRequest(c.Server, accountId, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) WatchlistMovies(ctx context.Context, accountId int32, params *WatchlistMoviesParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewWatchlistMoviesRequest(c.Server, accountId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) WatchlistTv(ctx context.Context, accountId int32, params *WatchlistTvParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewWatchlistTvRequest(c.Server, accountId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewDetailsRequest generates requests for Details
func NewDetailsRequest(server string, accountId int32, params *DetailsParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "account_id", accountId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "integer", Format: "int32"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/3/account/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.SessionId != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "session_id", *params.SessionId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewAddFavoriteRequest calls the generic AddFavorite builder with application/json body
func NewAddFavoriteRequest(server string, accountId int32, params *AddFavoriteParams, body AddFavoriteJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewAddFavoriteRequestWithBody(server, accountId, params, "application/json", bodyReader)
}

// NewAddFavoriteRequestWithBody generates requests for AddFavorite with any type of body
func NewAddFavoriteRequestWithBody(server string, accountId int32, params *AddFavoriteParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "account_id", accountId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "integer", Format: "int32"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/3/account/%s/favorite", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.SessionId != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "session_id", *params.SessionId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetFavoritesRequest generates requests for GetFavorites
func NewGetFavoritesRequest(server string, accountId int32, params *GetFavoritesParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "account_id", accountId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "integer", Format: "int32"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/3/account/%s/favorite/movies", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.Language != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "language", *params.Language, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.Page != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "page", *params.Page, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: "int32"}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.SessionId != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "session_id", *params.SessionId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.SortBy != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "sort_by", *params.SortBy, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewFavoriteTvRequest generates requests for FavoriteTv
func NewFavoriteTvRequest(server string, accountId int32, params *FavoriteTvParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "account_id", accountId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "integer", Format: "int32"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/3/account/%s/favorite/tv", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.Language != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "language", *params.Language, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.Page != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "page", *params.Page, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: "int32"}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.SessionId != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "session_id", *params.SessionId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.SortBy != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "sort_by", *params.SortBy, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewListsRequest generates requests for Lists
func NewListsRequest(server string, accountId int32, params *ListsParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "account_id", accountId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "integer", Format: "int32"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/3/account/%s/lists", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.Page != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "page", *params.Page, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: "int32"}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.SessionId != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "session_id", *params.SessionId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewRatedMoviesRequest generates requests for RatedMovies
func NewRatedMoviesRequest(server string, accountId int32, params *RatedMoviesParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "account_id", accountId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "integer", Format: "int32"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/3/account/%s/rated/movies", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.Language != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "language", *params.Language, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.Page != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "page", *params.Page, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: "int32"}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.SessionId != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "session_id", *params.SessionId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.SortBy != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "sort_by", *params.SortBy, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewRatedTvRequest generates requests for RatedTv
func NewRatedTvRequest(server string, accountId int32, params *RatedTvParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "account_id", accountId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "integer", Format: "int32"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/3/account/%s/rated/tv", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.Language != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "language", *params.Language, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.Page != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "page", *params.Page, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: "int32"}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.SessionId != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "session_id", *params.SessionId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.SortBy != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "sort_by", *params.SortBy, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewRatedTvEpisodesRequest generates requests for RatedTvEpisodes
func NewRatedTvEpisodesRequest(server string, accountId int32, params *RatedTvEpisodesParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "account_id", accountId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "integer", Format: "int32"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/3/account/%s/rated/tv/episodes", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.Language != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "language", *params.Language, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.Page != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "page", *params.Page, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: "int32"}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.SessionId != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "session_id", *params.SessionId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.SortBy != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "sort_by", *params.SortBy, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewAddToWatchlistRequest calls the generic AddToWatchlist builder with application/json body
func NewAddToWatchlistRequest(server string, accountId int32, params *AddToWatchlistParams, body AddToWatchlistJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewAddToWatchlistRequestWithBody(server, accountId, params, "application/json", bodyReader)
}

// NewAddToWatchlistRequestWithBody generates requests for AddToWatchlist with any type of body
func NewAddToWatchlistRequestWithBody(server string, accountId int32, params *AddToWatchlistParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "account_id", accountId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "integer", Format: "int32"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/3/account/%s/watchlist", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.SessionId != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "session_id", *params.SessionId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewWatchlistMoviesRequest generates requests for WatchlistMovies
func NewWatchlistMoviesRequest(server string, accountId int32, params *WatchlistMoviesParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "account_id", accountId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "integer", Format: "int32"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/3/account/%s/watchlist/movies", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.Language != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "language", *params.Language, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.Page != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "page", *params.Page, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: "int32"}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.SessionId != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "session_id", *params.SessionId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.SortBy != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "sort_by", *params.SortBy, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewWatchlistTvRequest generates requests for WatchlistTv
func NewWatchlistTvRequest(server string, accountId int32, params *WatchlistTvParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "account_id", accountId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "integer", Format: "int32"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/3/account/%s/watchlist/tv", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.Language != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "language", *params.Language, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.Page != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "page", *params.Page, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: "int32"}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.SessionId != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "session_id", *params.SessionId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.SortBy != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "sort_by", *params.SortBy, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// DetailsWithResponse request
	DetailsWithResponse(ctx context.Context, accountId int32, params *DetailsParams, reqEditors ...RequestEditorFn) (*DetailsResponse, error)

	// AddFavoriteWithBodyWithResponse request with any body
	AddFavoriteWithBodyWithResponse(ctx context.Context, accountId int32, params *AddFavoriteParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*AddFavoriteResponse, error)

	AddFavoriteWithResponse(ctx context.Context, accountId int32, params *AddFavoriteParams, body AddFavoriteJSONRequestBody, reqEditors ...RequestEditorFn) (*AddFavoriteResponse, error)

	// GetFavoritesWithResponse request
	GetFavoritesWithResponse(ctx context.Context, accountId int32, params *GetFavoritesParams, reqEditors ...RequestEditorFn) (*GetFavoritesResponse, error)

	// FavoriteTvWithResponse request
	FavoriteTvWithResponse(ctx context.Context, accountId int32, params *FavoriteTvParams, reqEditors ...RequestEditorFn) (*FavoriteTvResponse, error)

	// ListsWithResponse request
	ListsWithResponse(ctx context.Context, accountId int32, params *ListsParams, reqEditors ...RequestEditorFn) (*ListsResponse, error)

	// RatedMoviesWithResponse request
	RatedMoviesWithResponse(ctx context.Context, accountId int32, params *RatedMoviesParams, reqEditors ...RequestEditorFn) (*RatedMoviesResponse, error)

	// RatedTvWithResponse request
	RatedTvWithResponse(ctx context.Context, accountId int32, params *RatedTvParams, reqEditors ...RequestEditorFn) (*RatedTvResponse, error)

	// RatedTvEpisodesWithResponse request
	RatedTvEpisodesWithResponse(ctx context.Context, accountId int32, params *RatedTvEpisodesParams, reqEditors ...RequestEditorFn) (*RatedTvEpisodesResponse, error)

	// AddToWatchlistWithBodyWithResponse request with any body
	AddToWatchlistWithBodyWithResponse(ctx context.Context, accountId int32, params *AddToWatchlistParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*AddToWatchlistResponse, error)

	AddToWatchlistWithResponse(ctx context.Context, accountId int32, params *AddToWatchlistParams, body AddToWatchlistJSONRequestBody, reqEditors ...RequestEditorFn) (*AddToWatchlistResponse, error)

	// WatchlistMoviesWithResponse request
	WatchlistMoviesWithResponse(ctx context.Context, accountId int32, params *WatchlistMoviesParams, reqEditors ...RequestEditorFn) (*WatchlistMoviesResponse, error)

	// WatchlistTvWithResponse request
	WatchlistTvWithResponse(ctx context.Context, accountId int32, params *WatchlistTvParams, reqEditors ...RequestEditorFn) (*WatchlistTvResponse, error)
}

type DetailsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Avatar *struct {
			Gravatar *struct {
				Hash *string `json:"hash,omitempty"`
			} `json:"gravatar,omitempty"`
			Tmdb *struct {
				AvatarPath *string `json:"avatar_path,omitempty"`
			} `json:"tmdb,omitempty"`
		} `json:"avatar,omitempty"`
		Id           *int    `json:"id,omitempty"`
		IncludeAdult *bool   `json:"include_adult,omitempty"`
		Iso31661     *string `json:"iso_3166_1,omitempty"`
		Iso6391      *string `json:"iso_639_1,omitempty"`
		Name         *string `json:"name,omitempty"`
		Username     *string `json:"username,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r DetailsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DetailsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r DetailsResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type AddFavoriteResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		StatusCode    *int    `json:"status_code,omitempty"`
		StatusMessage *string `json:"status_message,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r AddFavoriteResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r AddFavoriteResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r AddFavoriteResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetFavoritesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Page    *int `json:"page,omitempty"`
		Results *[]struct {
			Adult            *bool    `json:"adult,omitempty"`
			BackdropPath     *string  `json:"backdrop_path,omitempty"`
			GenreIds         *[]int   `json:"genre_ids,omitempty"`
			Id               *int     `json:"id,omitempty"`
			OriginalLanguage *string  `json:"original_language,omitempty"`
			OriginalTitle    *string  `json:"original_title,omitempty"`
			Overview         *string  `json:"overview,omitempty"`
			Popularity       *float32 `json:"popularity,omitempty"`
			PosterPath       *string  `json:"poster_path,omitempty"`
			ReleaseDate      *string  `json:"release_date,omitempty"`
			Title            *string  `json:"title,omitempty"`
			Video            *bool    `json:"video,omitempty"`
			VoteAverage      *float32 `json:"vote_average,omitempty"`
			VoteCount        *int     `json:"vote_count,omitempty"`
		} `json:"results,omitempty"`
		TotalPages   *int `json:"total_pages,omitempty"`
		TotalResults *int `json:"total_results,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r GetFavoritesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetFavoritesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetFavoritesResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type FavoriteTvResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Page    *int `json:"page,omitempty"`
		Results *[]struct {
			Adult            *bool     `json:"adult,omitempty"`
			BackdropPath     *string   `json:"backdrop_path,omitempty"`
			FirstAirDate     *string   `json:"first_air_date,omitempty"`
			GenreIds         *[]int    `json:"genre_ids,omitempty"`
			Id               *int      `json:"id,omitempty"`
			Name             *string   `json:"name,omitempty"`
			OriginCountry    *[]string `json:"origin_country,omitempty"`
			OriginalLanguage *string   `json:"original_language,omitempty"`
			OriginalName     *string   `json:"original_name,omitempty"`
			Overview         *string   `json:"overview,omitempty"`
			Popularity       *float32  `json:"popularity,omitempty"`
			PosterPath       *string   `json:"poster_path,omitempty"`
			VoteAverage      *float32  `json:"vote_average,omitempty"`
			VoteCount        *int      `json:"vote_count,omitempty"`
		} `json:"results,omitempty"`
		TotalPages   *int `json:"total_pages,omitempty"`
		TotalResults *int `json:"total_results,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r FavoriteTvResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r FavoriteTvResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r FavoriteTvResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type ListsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Page    *int `json:"page,omitempty"`
		Results *[]struct {
			Description   *string     `json:"description,omitempty"`
			FavoriteCount *int        `json:"favorite_count,omitempty"`
			Id            *int        `json:"id,omitempty"`
			Iso6391       *string     `json:"iso_639_1,omitempty"`
			ItemCount     *int        `json:"item_count,omitempty"`
			ListType      *string     `json:"list_type,omitempty"`
			Name          *string     `json:"name,omitempty"`
			PosterPath    interface{} `json:"poster_path,omitempty"`
		} `json:"results,omitempty"`
		TotalPages   *int `json:"total_pages,omitempty"`
		TotalResults *int `json:"total_results,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r ListsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ListsResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type RatedMoviesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Page    *int `json:"page,omitempty"`
		Results *[]struct {
			Adult            *bool    `json:"adult,omitempty"`
			BackdropPath     *string  `json:"backdrop_path,omitempty"`
			GenreIds         *[]int   `json:"genre_ids,omitempty"`
			Id               *int     `json:"id,omitempty"`
			OriginalLanguage *string  `json:"original_language,omitempty"`
			OriginalTitle    *string  `json:"original_title,omitempty"`
			Overview         *string  `json:"overview,omitempty"`
			Popularity       *float32 `json:"popularity,omitempty"`
			PosterPath       *string  `json:"poster_path,omitempty"`
			Rating           *int     `json:"rating,omitempty"`
			ReleaseDate      *string  `json:"release_date,omitempty"`
			Title            *string  `json:"title,omitempty"`
			Video            *bool    `json:"video,omitempty"`
			VoteAverage      *float32 `json:"vote_average,omitempty"`
			VoteCount        *int     `json:"vote_count,omitempty"`
		} `json:"results,omitempty"`
		TotalPages   *int `json:"total_pages,omitempty"`
		TotalResults *int `json:"total_results,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r RatedMoviesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r RatedMoviesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r RatedMoviesResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type RatedTvResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Page    *int `json:"page,omitempty"`
		Results *[]struct {
			Adult            *bool     `json:"adult,omitempty"`
			BackdropPath     *string   `json:"backdrop_path,omitempty"`
			FirstAirDate     *string   `json:"first_air_date,omitempty"`
			GenreIds         *[]int    `json:"genre_ids,omitempty"`
			Id               *int      `json:"id,omitempty"`
			Name             *string   `json:"name,omitempty"`
			OriginCountry    *[]string `json:"origin_country,omitempty"`
			OriginalLanguage *string   `json:"original_language,omitempty"`
			OriginalName     *string   `json:"original_name,omitempty"`
			Overview         *string   `json:"overview,omitempty"`
			Popularity       *float32  `json:"popularity,omitempty"`
			PosterPath       *string   `json:"poster_path,omitempty"`
			Rating           *int      `json:"rating,omitempty"`
			VoteAverage      *float32  `json:"vote_average,omitempty"`
			VoteCount        *int      `json:"vote_count,omitempty"`
		} `json:"results,omitempty"`
		TotalPages   *int `json:"total_pages,omitempty"`
		TotalResults *int `json:"total_results,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r RatedTvResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r RatedTvResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r RatedTvResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type RatedTvEpisodesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Page    *int `json:"page,omitempty"`
		Results *[]struct {
			AirDate        *string  `json:"air_date,omitempty"`
			EpisodeNumber  *int     `json:"episode_number,omitempty"`
			Id             *int     `json:"id,omitempty"`
			Name           *string  `json:"name,omitempty"`
			Overview       *string  `json:"overview,omitempty"`
			ProductionCode *string  `json:"production_code,omitempty"`
			Rating         *int     `json:"rating,omitempty"`
			Runtime        *int     `json:"runtime,omitempty"`
			SeasonNumber   *int     `json:"season_number,omitempty"`
			ShowId         *int     `json:"show_id,omitempty"`
			StillPath      *string  `json:"still_path,omitempty"`
			VoteAverage    *float32 `json:"vote_average,omitempty"`
			VoteCount      *int     `json:"vote_count,omitempty"`
		} `json:"results,omitempty"`
		TotalPages   *int `json:"total_pages,omitempty"`
		TotalResults *int `json:"total_results,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r RatedTvEpisodesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r RatedTvEpisodesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r RatedTvEpisodesResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type AddToWatchlistResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		StatusCode    *int    `json:"status_code,omitempty"`
		StatusMessage *string `json:"status_message,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r AddToWatchlistResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r AddToWatchlistResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r AddToWatchlistResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type WatchlistMoviesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Page    *int `json:"page,omitempty"`
		Results *[]struct {
			Adult            *bool    `json:"adult,omitempty"`
			BackdropPath     *string  `json:"backdrop_path,omitempty"`
			GenreIds         *[]int   `json:"genre_ids,omitempty"`
			Id               *int     `json:"id,omitempty"`
			OriginalLanguage *string  `json:"original_language,omitempty"`
			OriginalTitle    *string  `json:"original_title,omitempty"`
			Overview         *string  `json:"overview,omitempty"`
			Popularity       *float32 `json:"popularity,omitempty"`
			PosterPath       *string  `json:"poster_path,omitempty"`
			ReleaseDate      *string  `json:"release_date,omitempty"`
			Title            *string  `json:"title,omitempty"`
			Video            *bool    `json:"video,omitempty"`
			VoteAverage      *float32 `json:"vote_average,omitempty"`
			VoteCount        *int     `json:"vote_count,omitempty"`
		} `json:"results,omitempty"`
		TotalPages   *int `json:"total_pages,omitempty"`
		TotalResults *int `json:"total_results,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r WatchlistMoviesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r WatchlistMoviesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r WatchlistMoviesResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type WatchlistTvResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Page    *int `json:"page,omitempty"`
		Results *[]struct {
			Adult            *bool     `json:"adult,omitempty"`
			BackdropPath     *string   `json:"backdrop_path,omitempty"`
			FirstAirDate     *string   `json:"first_air_date,omitempty"`
			GenreIds         *[]int    `json:"genre_ids,omitempty"`
			Id               *int      `json:"id,omitempty"`
			Name             *string   `json:"name,omitempty"`
			OriginCountry    *[]string `json:"origin_country,omitempty"`
			OriginalLanguage *string   `json:"original_language,omitempty"`
			OriginalName     *string   `json:"original_name,omitempty"`
			Overview         *string   `json:"overview,omitempty"`
			Popularity       *float32  `json:"popularity,omitempty"`
			PosterPath       *string   `json:"poster_path,omitempty"`
			VoteAverage      *float32  `json:"vote_average,omitempty"`
			VoteCount        *int      `json:"vote_count,omitempty"`
		} `json:"results,omitempty"`
		TotalPages   *int `json:"total_pages,omitempty"`
		TotalResults *int `json:"total_results,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r WatchlistTvResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r WatchlistTvResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r WatchlistTvResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// DetailsWithResponse request returning *DetailsResponse
func (c *ClientWithResponses) DetailsWithResponse(ctx context.Context, accountId int32, params *DetailsParams, reqEditors ...RequestEditorFn) (*DetailsResponse, error) {
	rsp, err := c.Details(ctx, accountId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDetailsResponse(rsp)
}

// AddFavoriteWithBodyWithResponse request with arbitrary body returning *AddFavoriteResponse
func (c *ClientWithResponses) AddFavoriteWithBodyWithResponse(ctx context.Context, accountId int32, params *AddFavoriteParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*AddFavoriteResponse, error) {
	rsp, err := c.AddFavoriteWithBody(ctx, accountId, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseAddFavoriteResponse(rsp)
}

func (c *ClientWithResponses) AddFavoriteWithResponse(ctx context.Context, accountId int32, params *AddFavoriteParams, body AddFavoriteJSONRequestBody, reqEditors ...RequestEditorFn) (*AddFavoriteResponse, error) {
	rsp, err := c.AddFavorite(ctx, accountId, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseAddFavoriteResponse(rsp)
}

// GetFavoritesWithResponse request returning *GetFavoritesResponse
func (c *ClientWithResponses) GetFavoritesWithResponse(ctx context.Context, accountId int32, params *GetFavoritesParams, reqEditors ...RequestEditorFn) (*GetFavoritesResponse, error) {
	rsp, err := c.GetFavorites(ctx, accountId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetFavoritesResponse(rsp)
}

// FavoriteTvWithResponse request returning *FavoriteTvResponse
func (c *ClientWithResponses) FavoriteTvWithResponse(ctx context.Context, accountId int32, params *FavoriteTvParams, reqEditors ...RequestEditorFn) (*FavoriteTvResponse, error) {
	rsp, err := c.FavoriteTv(ctx, accountId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseFavoriteTvResponse(rsp)
}

// ListsWithResponse request returning *ListsResponse
func (c *ClientWithResponses) ListsWithResponse(ctx context.Context, accountId int32, params *ListsParams, reqEditors ...RequestEditorFn) (*ListsResponse, error) {
	rsp, err := c.Lists(ctx, accountId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListsResponse(rsp)
}

// RatedMoviesWithResponse request returning *RatedMoviesResponse
func (c *ClientWithResponses) RatedMoviesWithResponse(ctx context.Context, accountId int32, params *RatedMoviesParams, reqEditors ...RequestEditorFn) (*RatedMoviesResponse, error) {
	rsp, err := c.RatedMovies(ctx, accountId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRatedMoviesResponse(rsp)
}

// RatedTvWithResponse request returning *RatedTvResponse
func (c *ClientWithResponses) RatedTvWithResponse(ctx context.Context, accountId int32, params *RatedTvParams, reqEditors ...RequestEditorFn) (*RatedTvResponse, error) {
	rsp, err := c.RatedTv(ctx, accountId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRatedTvResponse(rsp)
}

// RatedTvEpisodesWithResponse request returning *RatedTvEpisodesResponse
func (c *ClientWithResponses) RatedTvEpisodesWithResponse(ctx context.Context, accountId int32, params *RatedTvEpisodesParams, reqEditors ...RequestEditorFn) (*RatedTvEpisodesResponse, error) {
	rsp, err := c.RatedTvEpisodes(ctx, accountId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRatedTvEpisodesResponse(rsp)
}

// AddToWatchlistWithBodyWithResponse request with arbitrary body returning *AddToWatchlistResponse
func (c *ClientWithResponses) AddToWatchlistWithBodyWithResponse(ctx context.Context, accountId int32, params *AddToWatchlistParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*AddToWatchlistResponse, error) {
	rsp, err := c.AddToWatchlistWithBody(ctx, accountId, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseAddToWatchlistResponse(rsp)
}

func (c *ClientWithResponses) AddToWatchlistWithResponse(ctx context.Context, accountId int32, params *AddToWatchlistParams, body AddToWatchlistJSONRequestBody, reqEditors ...RequestEditorFn) (*AddToWatchlistResponse, error) {
	rsp, err := c.AddToWatchlist(ctx, accountId, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseAddToWatchlistResponse(rsp)
}

// WatchlistMoviesWithResponse request returning *WatchlistMoviesResponse
func (c *ClientWithResponses) WatchlistMoviesWithResponse(ctx context.Context, accountId int32, params *WatchlistMoviesParams, reqEditors ...RequestEditorFn) (*WatchlistMoviesResponse, error) {
	rsp, err := c.WatchlistMovies(ctx, accountId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseWatchlistMoviesResponse(rsp)
}

// WatchlistTvWithResponse request returning *WatchlistTvResponse
func (c *ClientWithResponses) WatchlistTvWithResponse(ctx context.Context, accountId int32, params *WatchlistTvParams, reqEditors ...RequestEditorFn) (*WatchlistTvResponse, error) {
	rsp, err := c.WatchlistTv(ctx, accountId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseWatchlistTvResponse(rsp)
}

// ParseDetailsResponse parses an HTTP response from a DetailsWithResponse call
func ParseDetailsResponse(rsp *http.Response) (*DetailsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DetailsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Avatar *struct {
				Gravatar *struct {
					Hash *string `json:"hash,omitempty"`
				} `json:"gravatar,omitempty"`
				Tmdb *struct {
					AvatarPath *string `json:"avatar_path,omitempty"`
				} `json:"tmdb,omitempty"`
			} `json:"avatar,omitempty"`
			Id           *int    `json:"id,omitempty"`
			IncludeAdult *bool   `json:"include_adult,omitempty"`
			Iso31661     *string `json:"iso_3166_1,omitempty"`
			Iso6391      *string `json:"iso_639_1,omitempty"`
			Name         *string `json:"name,omitempty"`
			Username     *string `json:"username,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseAddFavoriteResponse parses an HTTP response from a AddFavoriteWithResponse call
func ParseAddFavoriteResponse(rsp *http.Response) (*AddFavoriteResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &AddFavoriteResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			StatusCode    *int    `json:"status_code,omitempty"`
			StatusMessage *string `json:"status_message,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetFavoritesResponse parses an HTTP response from a GetFavoritesWithResponse call
func ParseGetFavoritesResponse(rsp *http.Response) (*GetFavoritesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetFavoritesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Page    *int `json:"page,omitempty"`
			Results *[]struct {
				Adult            *bool    `json:"adult,omitempty"`
				BackdropPath     *string  `json:"backdrop_path,omitempty"`
				GenreIds         *[]int   `json:"genre_ids,omitempty"`
				Id               *int     `json:"id,omitempty"`
				OriginalLanguage *string  `json:"original_language,omitempty"`
				OriginalTitle    *string  `json:"original_title,omitempty"`
				Overview         *string  `json:"overview,omitempty"`
				Popularity       *float32 `json:"popularity,omitempty"`
				PosterPath       *string  `json:"poster_path,omitempty"`
				ReleaseDate      *string  `json:"release_date,omitempty"`
				Title            *string  `json:"title,omitempty"`
				Video            *bool    `json:"video,omitempty"`
				VoteAverage      *float32 `json:"vote_average,omitempty"`
				VoteCount        *int     `json:"vote_count,omitempty"`
			} `json:"results,omitempty"`
			TotalPages   *int `json:"total_pages,omitempty"`
			TotalResults *int `json:"total_results,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseFavoriteTvResponse parses an HTTP response from a FavoriteTvWithResponse call
func ParseFavoriteTvResponse(rsp *http.Response) (*FavoriteTvResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &FavoriteTvResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Page    *int `json:"page,omitempty"`
			Results *[]struct {
				Adult            *bool     `json:"adult,omitempty"`
				BackdropPath     *string   `json:"backdrop_path,omitempty"`
				FirstAirDate     *string   `json:"first_air_date,omitempty"`
				GenreIds         *[]int    `json:"genre_ids,omitempty"`
				Id               *int      `json:"id,omitempty"`
				Name             *string   `json:"name,omitempty"`
				OriginCountry    *[]string `json:"origin_country,omitempty"`
				OriginalLanguage *string   `json:"original_language,omitempty"`
				OriginalName     *string   `json:"original_name,omitempty"`
				Overview         *string   `json:"overview,omitempty"`
				Popularity       *float32  `json:"popularity,omitempty"`
				PosterPath       *string   `json:"poster_path,omitempty"`
				VoteAverage      *float32  `json:"vote_average,omitempty"`
				VoteCount        *int      `json:"vote_count,omitempty"`
			} `json:"results,omitempty"`
			TotalPages   *int `json:"total_pages,omitempty"`
			TotalResults *int `json:"total_results,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseListsResponse parses an HTTP response from a ListsWithResponse call
func ParseListsResponse(rsp *http.Response) (*ListsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Page    *int `json:"page,omitempty"`
			Results *[]struct {
				Description   *string     `json:"description,omitempty"`
				FavoriteCount *int        `json:"favorite_count,omitempty"`
				Id            *int        `json:"id,omitempty"`
				Iso6391       *string     `json:"iso_639_1,omitempty"`
				ItemCount     *int        `json:"item_count,omitempty"`
				ListType      *string     `json:"list_type,omitempty"`
				Name          *string     `json:"name,omitempty"`
				PosterPath    interface{} `json:"poster_path,omitempty"`
			} `json:"results,omitempty"`
			TotalPages   *int `json:"total_pages,omitempty"`
			TotalResults *int `json:"total_results,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseRatedMoviesResponse parses an HTTP response from a RatedMoviesWithResponse call
func ParseRatedMoviesResponse(rsp *http.Response) (*RatedMoviesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &RatedMoviesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Page    *int `json:"page,omitempty"`
			Results *[]struct {
				Adult            *bool    `json:"adult,omitempty"`
				BackdropPath     *string  `json:"backdrop_path,omitempty"`
				GenreIds         *[]int   `json:"genre_ids,omitempty"`
				Id               *int     `json:"id,omitempty"`
				OriginalLanguage *string  `json:"original_language,omitempty"`
				OriginalTitle    *string  `json:"original_title,omitempty"`
				Overview         *string  `json:"overview,omitempty"`
				Popularity       *float32 `json:"popularity,omitempty"`
				PosterPath       *string  `json:"poster_path,omitempty"`
				Rating           *int     `json:"rating,omitempty"`
				ReleaseDate      *string  `json:"release_date,omitempty"`
				Title            *string  `json:"title,omitempty"`
				Video            *bool    `json:"video,omitempty"`
				VoteAverage      *float32 `json:"vote_average,omitempty"`
				VoteCount        *int     `json:"vote_count,omitempty"`
			} `json:"results,omitempty"`
			TotalPages   *int `json:"total_pages,omitempty"`
			TotalResults *int `json:"total_results,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseRatedTvResponse parses an HTTP response from a RatedTvWithResponse call
func ParseRatedTvResponse(rsp *http.Response) (*RatedTvResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &RatedTvResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Page    *int `json:"page,omitempty"`
			Results *[]struct {
				Adult            *bool     `json:"adult,omitempty"`
				BackdropPath     *string   `json:"backdrop_path,omitempty"`
				FirstAirDate     *string   `json:"first_air_date,omitempty"`
				GenreIds         *[]int    `json:"genre_ids,omitempty"`
				Id               *int      `json:"id,omitempty"`
				Name             *string   `json:"name,omitempty"`
				OriginCountry    *[]string `json:"origin_country,omitempty"`
				OriginalLanguage *string   `json:"original_language,omitempty"`
				OriginalName     *string   `json:"original_name,omitempty"`
				Overview         *string   `json:"overview,omitempty"`
				Popularity       *float32  `json:"popularity,omitempty"`
				PosterPath       *string   `json:"poster_path,omitempty"`
				Rating           *int      `json:"rating,omitempty"`
				VoteAverage      *float32  `json:"vote_average,omitempty"`
				VoteCount        *int      `json:"vote_count,omitempty"`
			} `json:"results,omitempty"`
			TotalPages   *int `json:"total_pages,omitempty"`
			TotalResults *int `json:"total_results,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseRatedTvEpisodesResponse parses an HTTP response from a RatedTvEpisodesWithResponse call
func ParseRatedTvEpisodesResponse(rsp *http.Response) (*RatedTvEpisodesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &RatedTvEpisodesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Page    *int `json:"page,omitempty"`
			Results *[]struct {
				AirDate        *string  `json:"air_date,omitempty"`
				EpisodeNumber  *int     `json:"episode_number,omitempty"`
				Id             *int     `json:"id,omitempty"`
				Name           *string  `json:"name,omitempty"`
				Overview       *string  `json:"overview,omitempty"`
				ProductionCode *string  `json:"production_code,omitempty"`
				Rating         *int     `json:"rating,omitempty"`
				Runtime        *int     `json:"runtime,omitempty"`
				SeasonNumber   *int     `json:"season_number,omitempty"`
				ShowId         *int     `json:"show_id,omitempty"`
				StillPath      *string  `json:"still_path,omitempty"`
				VoteAverage    *float32 `json:"vote_average,omitempty"`
				VoteCount      *int     `json:"vote_count,omitempty"`
			} `json:"results,omitempty"`
			TotalPages   *int `json:"total_pages,omitempty"`
			TotalResults *int `json:"total_results,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseAddToWatchlistResponse parses an HTTP response from a AddToWatchlistWithResponse call
func ParseAddToWatchlistResponse(rsp *http.Response) (*AddToWatchlistResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &AddToWatchlistResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			StatusCode    *int    `json:"status_code,omitempty"`
			StatusMessage *string `json:"status_message,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseWatchlistMoviesResponse parses an HTTP response from a WatchlistMoviesWithResponse call
func ParseWatchlistMoviesResponse(rsp *http.Response) (*WatchlistMoviesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &WatchlistMoviesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Page    *int `json:"page,omitempty"`
			Results *[]struct {
				Adult            *bool    `json:"adult,omitempty"`
				BackdropPath     *string  `json:"backdrop_path,omitempty"`
				GenreIds         *[]int   `json:"genre_ids,omitempty"`
				Id               *int     `json:"id,omitempty"`
				OriginalLanguage *string  `json:"original_language,omitempty"`
				OriginalTitle    *string  `json:"original_title,omitempty"`
				Overview         *string  `json:"overview,omitempty"`
				Popularity       *float32 `json:"popularity,omitempty"`
				PosterPath       *string  `json:"poster_path,omitempty"`
				ReleaseDate      *string  `json:"release_date,omitempty"`
				Title            *string  `json:"title,omitempty"`
				Video            *bool    `json:"video,omitempty"`
				VoteAverage      *float32 `json:"vote_average,omitempty"`
				VoteCount        *int     `json:"vote_count,omitempty"`
			} `json:"results,omitempty"`
			TotalPages   *int `json:"total_pages,omitempty"`
			TotalResults *int `json:"total_results,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseWatchlistTvResponse parses an HTTP response from a WatchlistTvWithResponse call
func ParseWatchlistTvResponse(rsp *http.Response) (*WatchlistTvResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &WatchlistTvResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Page    *int `json:"page,omitempty"`
			Results *[]struct {
				Adult            *bool     `json:"adult,omitempty"`
				BackdropPath     *string   `json:"backdrop_path,omitempty"`
				FirstAirDate     *string   `json:"first_air_date,omitempty"`
				GenreIds         *[]int    `json:"genre_ids,omitempty"`
				Id               *int      `json:"id,omitempty"`
				Name             *string   `json:"name,omitempty"`
				OriginCountry    *[]string `json:"origin_country,omitempty"`
				OriginalLanguage *string   `json:"original_language,omitempty"`
				OriginalName     *string   `json:"original_name,omitempty"`
				Overview         *string   `json:"overview,omitempty"`
				Popularity       *float32  `json:"popularity,omitempty"`
				PosterPath       *string   `json:"poster_path,omitempty"`
				VoteAverage      *float32  `json:"vote_average,omitempty"`
				VoteCount        *int      `json:"vote_count,omitempty"`
			} `json:"results,omitempty"`
			TotalPages   *int `json:"total_pages,omitempty"`
			TotalResults *int `json:"total_results,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}
