// Package collection provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package collection

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
)

const (
	Sec0Scopes sec0ContextKey = "sec0.Scopes"
)

// sec0ContextKey is the context key for sec0 security scheme
type sec0ContextKey string

// DetailsParams defines parameters for Details.
type DetailsParams struct {
	Language *string `form:"language,omitempty" json:"language,omitempty"`
}

// ImagesParams defines parameters for Images.
type ImagesParams struct {
	// IncludeImageLanguage specify a comma separated list of ISO-639-1 values to query, for example: `en-US,null`
	IncludeImageLanguage *string `form:"include_image_language,omitempty" json:"include_image_language,omitempty"`
	Language             *string `form:"language,omitempty" json:"language,omitempty"`
}

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// Details request
	Details(ctx context.Context, collectionId int32, params *DetailsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// Images request
	Images(ctx context.Context, collectionId int32, params *ImagesParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// Translations request
	Translations(ctx context.Context, collectionId int32, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) Details(ctx context.Context, collectionId int32, params *DetailsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDetailsRequest(c.Server, collectionId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) Images(ctx context.Context, collectionId int32, params *ImagesParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewImagesRequest(c.Server, collectionId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) Translations(ctx context.Context, collectionId int32, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewTranslationsRequest(c.Server, collectionId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewDetailsRequest generates requests for Details
func NewDetailsRequest(server string, collectionId int32, params *DetailsParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "collection_id", collectionId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "integer", Format: "int32"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/3/collection/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.Language != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "language", *params.Language, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewImagesRequest generates requests for Images
func NewImagesRequest(server string, collectionId int32, params *ImagesParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "collection_id", collectionId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "integer", Format: "int32"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/3/collection/%s/images", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.IncludeImageLanguage != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "include_image_language", *params.IncludeImageLanguage, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.Language != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "language", *params.Language, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewTranslationsRequest generates requests for Translations
func NewTranslationsRequest(server string, collectionId int32) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "collection_id", collectionId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "integer", Format: "int32"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/3/collection/%s/translations", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// DetailsWithResponse request
	DetailsWithResponse(ctx context.Context, collectionId int32, params *DetailsParams, reqEditors ...RequestEditorFn) (*DetailsResponse, error)

	// ImagesWithResponse request
	ImagesWithResponse(ctx context.Context, collectionId int32, params *ImagesParams, reqEditors ...RequestEditorFn) (*ImagesResponse, error)

	// TranslationsWithResponse request
	TranslationsWithResponse(ctx context.Context, collectionId int32, reqEditors ...RequestEditorFn) (*TranslationsResponse, error)
}

type DetailsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		BackdropPath     *string `json:"backdrop_path,omitempty"`
		Id               *int    `json:"id,omitempty"`
		Name             *string `json:"name,omitempty"`
		OriginalLanguage *string `json:"original_language,omitempty"`
		OriginalName     *string `json:"original_name,omitempty"`
		Overview         *string `json:"overview,omitempty"`
		Parts            *[]struct {
			Adult            *bool    `json:"adult,omitempty"`
			BackdropPath     *string  `json:"backdrop_path,omitempty"`
			GenreIds         *[]int   `json:"genre_ids,omitempty"`
			Id               *int     `json:"id,omitempty"`
			MediaType        *string  `json:"media_type,omitempty"`
			Name             *string  `json:"name,omitempty"`
			OriginalLanguage *string  `json:"original_language,omitempty"`
			OriginalName     *string  `json:"original_name,omitempty"`
			Overview         *string  `json:"overview,omitempty"`
			Popularity       *float32 `json:"popularity,omitempty"`
			PosterPath       *string  `json:"poster_path,omitempty"`
			ReleaseDate      *string  `json:"release_date,omitempty"`
			Video            *bool    `json:"video,omitempty"`
			VoteAverage      *float32 `json:"vote_average,omitempty"`
			VoteCount        *int     `json:"vote_count,omitempty"`
		} `json:"parts,omitempty"`
		PosterPath *string `json:"poster_path,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r DetailsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DetailsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r DetailsResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type ImagesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Backdrops *[]struct {
			AspectRatio *float32    `json:"aspect_ratio,omitempty"`
			FilePath    *string     `json:"file_path,omitempty"`
			Height      *int        `json:"height,omitempty"`
			Iso6391     interface{} `json:"iso_639_1,omitempty"`
			VoteAverage *float32    `json:"vote_average,omitempty"`
			VoteCount   *int        `json:"vote_count,omitempty"`
			Width       *int        `json:"width,omitempty"`
		} `json:"backdrops,omitempty"`
		Id      *int `json:"id,omitempty"`
		Posters *[]struct {
			AspectRatio *float32 `json:"aspect_ratio,omitempty"`
			FilePath    *string  `json:"file_path,omitempty"`
			Height      *int     `json:"height,omitempty"`
			Iso6391     *string  `json:"iso_639_1,omitempty"`
			VoteAverage *float32 `json:"vote_average,omitempty"`
			VoteCount   *int     `json:"vote_count,omitempty"`
			Width       *int     `json:"width,omitempty"`
		} `json:"posters,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r ImagesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ImagesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ImagesResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type TranslationsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Id           *int `json:"id,omitempty"`
		Translations *[]struct {
			Data *struct {
				Homepage *string `json:"homepage,omitempty"`
				Overview *string `json:"overview,omitempty"`
				Title    *string `json:"title,omitempty"`
			} `json:"data,omitempty"`
			EnglishName *string `json:"english_name,omitempty"`
			Iso31661    *string `json:"iso_3166_1,omitempty"`
			Iso6391     *string `json:"iso_639_1,omitempty"`
			Name        *string `json:"name,omitempty"`
		} `json:"translations,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r TranslationsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r TranslationsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r TranslationsResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// DetailsWithResponse request returning *DetailsResponse
func (c *ClientWithResponses) DetailsWithResponse(ctx context.Context, collectionId int32, params *DetailsParams, reqEditors ...RequestEditorFn) (*DetailsResponse, error) {
	rsp, err := c.Details(ctx, collectionId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDetailsResponse(rsp)
}

// ImagesWithResponse request returning *ImagesResponse
func (c *ClientWithResponses) ImagesWithResponse(ctx context.Context, collectionId int32, params *ImagesParams, reqEditors ...RequestEditorFn) (*ImagesResponse, error) {
	rsp, err := c.Images(ctx, collectionId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseImagesResponse(rsp)
}

// TranslationsWithResponse request returning *TranslationsResponse
func (c *ClientWithResponses) TranslationsWithResponse(ctx context.Context, collectionId int32, reqEditors ...RequestEditorFn) (*TranslationsResponse, error) {
	rsp, err := c.Translations(ctx, collectionId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseTranslationsResponse(rsp)
}

// ParseDetailsResponse parses an HTTP response from a DetailsWithResponse call
func ParseDetailsResponse(rsp *http.Response) (*DetailsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DetailsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			BackdropPath     *string `json:"backdrop_path,omitempty"`
			Id               *int    `json:"id,omitempty"`
			Name             *string `json:"name,omitempty"`
			OriginalLanguage *string `json:"original_language,omitempty"`
			OriginalName     *string `json:"original_name,omitempty"`
			Overview         *string `json:"overview,omitempty"`
			Parts            *[]struct {
				Adult            *bool    `json:"adult,omitempty"`
				BackdropPath     *string  `json:"backdrop_path,omitempty"`
				GenreIds         *[]int   `json:"genre_ids,omitempty"`
				Id               *int     `json:"id,omitempty"`
				MediaType        *string  `json:"media_type,omitempty"`
				Name             *string  `json:"name,omitempty"`
				OriginalLanguage *string  `json:"original_language,omitempty"`
				OriginalName     *string  `json:"original_name,omitempty"`
				Overview         *string  `json:"overview,omitempty"`
				Popularity       *float32 `json:"popularity,omitempty"`
				PosterPath       *string  `json:"poster_path,omitempty"`
				ReleaseDate      *string  `json:"release_date,omitempty"`
				Video            *bool    `json:"video,omitempty"`
				VoteAverage      *float32 `json:"vote_average,omitempty"`
				VoteCount        *int     `json:"vote_count,omitempty"`
			} `json:"parts,omitempty"`
			PosterPath *string `json:"poster_path,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseImagesResponse parses an HTTP response from a ImagesWithResponse call
func ParseImagesResponse(rsp *http.Response) (*ImagesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ImagesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Backdrops *[]struct {
				AspectRatio *float32    `json:"aspect_ratio,omitempty"`
				FilePath    *string     `json:"file_path,omitempty"`
				Height      *int        `json:"height,omitempty"`
				Iso6391     interface{} `json:"iso_639_1,omitempty"`
				VoteAverage *float32    `json:"vote_average,omitempty"`
				VoteCount   *int        `json:"vote_count,omitempty"`
				Width       *int        `json:"width,omitempty"`
			} `json:"backdrops,omitempty"`
			Id      *int `json:"id,omitempty"`
			Posters *[]struct {
				AspectRatio *float32 `json:"aspect_ratio,omitempty"`
				FilePath    *string  `json:"file_path,omitempty"`
				Height      *int     `json:"height,omitempty"`
				Iso6391     *string  `json:"iso_639_1,omitempty"`
				VoteAverage *float32 `json:"vote_average,omitempty"`
				VoteCount   *int     `json:"vote_count,omitempty"`
				Width       *int     `json:"width,omitempty"`
			} `json:"posters,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseTranslationsResponse parses an HTTP response from a TranslationsWithResponse call
func ParseTranslationsResponse(rsp *http.Response) (*TranslationsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &TranslationsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Id           *int `json:"id,omitempty"`
			Translations *[]struct {
				Data *struct {
					Homepage *string `json:"homepage,omitempty"`
					Overview *string `json:"overview,omitempty"`
					Title    *string `json:"title,omitempty"`
				} `json:"data,omitempty"`
				EnglishName *string `json:"english_name,omitempty"`
				Iso31661    *string `json:"iso_3166_1,omitempty"`
				Iso6391     *string `json:"iso_639_1,omitempty"`
				Name        *string `json:"name,omitempty"`
			} `json:"translations,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}
