// Package watch provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package watch

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
)

const (
	Sec0Scopes sec0ContextKey = "sec0.Scopes"
)

// sec0ContextKey is the context key for sec0 security scheme
type sec0ContextKey string

// ProvidersMovieListParams defines parameters for ProvidersMovieList.
type ProvidersMovieListParams struct {
	Language    *string `form:"language,omitempty" json:"language,omitempty"`
	WatchRegion *string `form:"watch_region,omitempty" json:"watch_region,omitempty"`
}

// ProvidersAvailableRegionsParams defines parameters for ProvidersAvailableRegions.
type ProvidersAvailableRegionsParams struct {
	Language *string `form:"language,omitempty" json:"language,omitempty"`
}

// ProviderTvListParams defines parameters for ProviderTvList.
type ProviderTvListParams struct {
	Language    *string `form:"language,omitempty" json:"language,omitempty"`
	WatchRegion *string `form:"watch_region,omitempty" json:"watch_region,omitempty"`
}

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// ProvidersMovieList request
	ProvidersMovieList(ctx context.Context, params *ProvidersMovieListParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ProvidersAvailableRegions request
	ProvidersAvailableRegions(ctx context.Context, params *ProvidersAvailableRegionsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ProviderTvList request
	ProviderTvList(ctx context.Context, params *ProviderTvListParams, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) ProvidersMovieList(ctx context.Context, params *ProvidersMovieListParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewProvidersMovieListRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ProvidersAvailableRegions(ctx context.Context, params *ProvidersAvailableRegionsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewProvidersAvailableRegionsRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ProviderTvList(ctx context.Context, params *ProviderTvListParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewProviderTvListRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewProvidersMovieListRequest generates requests for ProvidersMovieList
func NewProvidersMovieListRequest(server string, params *ProvidersMovieListParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/3/watch/providers/movie")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.Language != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "language", *params.Language, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.WatchRegion != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "watch_region", *params.WatchRegion, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewProvidersAvailableRegionsRequest generates requests for ProvidersAvailableRegions
func NewProvidersAvailableRegionsRequest(server string, params *ProvidersAvailableRegionsParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/3/watch/providers/regions")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.Language != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "language", *params.Language, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewProviderTvListRequest generates requests for ProviderTvList
func NewProviderTvListRequest(server string, params *ProviderTvListParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/3/watch/providers/tv")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.Language != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "language", *params.Language, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.WatchRegion != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "watch_region", *params.WatchRegion, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// ProvidersMovieListWithResponse request
	ProvidersMovieListWithResponse(ctx context.Context, params *ProvidersMovieListParams, reqEditors ...RequestEditorFn) (*ProvidersMovieListResponse, error)

	// ProvidersAvailableRegionsWithResponse request
	ProvidersAvailableRegionsWithResponse(ctx context.Context, params *ProvidersAvailableRegionsParams, reqEditors ...RequestEditorFn) (*ProvidersAvailableRegionsResponse, error)

	// ProviderTvListWithResponse request
	ProviderTvListWithResponse(ctx context.Context, params *ProviderTvListParams, reqEditors ...RequestEditorFn) (*ProviderTvListResponse, error)
}

type ProvidersMovieListResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Results *[]struct {
			DisplayPriorities *struct {
				AE *int `json:"AE,omitempty"`
				AR *int `json:"AR,omitempty"`
				AT *int `json:"AT,omitempty"`
				AU *int `json:"AU,omitempty"`
				BE *int `json:"BE,omitempty"`
				BG *int `json:"BG,omitempty"`
				BO *int `json:"BO,omitempty"`
				BR *int `json:"BR,omitempty"`
				CA *int `json:"CA,omitempty"`
				CH *int `json:"CH,omitempty"`
				CL *int `json:"CL,omitempty"`
				CO *int `json:"CO,omitempty"`
				CR *int `json:"CR,omitempty"`
				CV *int `json:"CV,omitempty"`
				CZ *int `json:"CZ,omitempty"`
				DE *int `json:"DE,omitempty"`
				DK *int `json:"DK,omitempty"`
				EC *int `json:"EC,omitempty"`
				EE *int `json:"EE,omitempty"`
				EG *int `json:"EG,omitempty"`
				ES *int `json:"ES,omitempty"`
				FI *int `json:"FI,omitempty"`
				FR *int `json:"FR,omitempty"`
				GB *int `json:"GB,omitempty"`
				GH *int `json:"GH,omitempty"`
				GR *int `json:"GR,omitempty"`
				GT *int `json:"GT,omitempty"`
				HK *int `json:"HK,omitempty"`
				HN *int `json:"HN,omitempty"`
				HU *int `json:"HU,omitempty"`
				ID *int `json:"ID,omitempty"`
				IE *int `json:"IE,omitempty"`
				IL *int `json:"IL,omitempty"`
				IN *int `json:"IN,omitempty"`
				IT *int `json:"IT,omitempty"`
				JP *int `json:"JP,omitempty"`
				LT *int `json:"LT,omitempty"`
				LV *int `json:"LV,omitempty"`
				MU *int `json:"MU,omitempty"`
				MX *int `json:"MX,omitempty"`
				MY *int `json:"MY,omitempty"`
				MZ *int `json:"MZ,omitempty"`
				NL *int `json:"NL,omitempty"`
				NO *int `json:"NO,omitempty"`
				NZ *int `json:"NZ,omitempty"`
				PE *int `json:"PE,omitempty"`
				PH *int `json:"PH,omitempty"`
				PL *int `json:"PL,omitempty"`
				PT *int `json:"PT,omitempty"`
				PY *int `json:"PY,omitempty"`
				RU *int `json:"RU,omitempty"`
				SA *int `json:"SA,omitempty"`
				SE *int `json:"SE,omitempty"`
				SG *int `json:"SG,omitempty"`
				SI *int `json:"SI,omitempty"`
				SK *int `json:"SK,omitempty"`
				TH *int `json:"TH,omitempty"`
				TR *int `json:"TR,omitempty"`
				TW *int `json:"TW,omitempty"`
				UG *int `json:"UG,omitempty"`
				US *int `json:"US,omitempty"`
				VE *int `json:"VE,omitempty"`
				ZA *int `json:"ZA,omitempty"`
			} `json:"display_priorities,omitempty"`
			DisplayPriority *int    `json:"display_priority,omitempty"`
			LogoPath        *string `json:"logo_path,omitempty"`
			ProviderId      *int    `json:"provider_id,omitempty"`
			ProviderName    *string `json:"provider_name,omitempty"`
		} `json:"results,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r ProvidersMovieListResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ProvidersMovieListResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ProvidersMovieListResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type ProvidersAvailableRegionsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Results *[]struct {
			EnglishName *string `json:"english_name,omitempty"`
			Iso31661    *string `json:"iso_3166_1,omitempty"`
			NativeName  *string `json:"native_name,omitempty"`
		} `json:"results,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r ProvidersAvailableRegionsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ProvidersAvailableRegionsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ProvidersAvailableRegionsResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type ProviderTvListResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Results *[]struct {
			DisplayPriorities *struct {
				AE *int `json:"AE,omitempty"`
				AR *int `json:"AR,omitempty"`
				AT *int `json:"AT,omitempty"`
				AU *int `json:"AU,omitempty"`
				BE *int `json:"BE,omitempty"`
				BG *int `json:"BG,omitempty"`
				BO *int `json:"BO,omitempty"`
				BR *int `json:"BR,omitempty"`
				CA *int `json:"CA,omitempty"`
				CH *int `json:"CH,omitempty"`
				CL *int `json:"CL,omitempty"`
				CO *int `json:"CO,omitempty"`
				CR *int `json:"CR,omitempty"`
				CV *int `json:"CV,omitempty"`
				CZ *int `json:"CZ,omitempty"`
				DE *int `json:"DE,omitempty"`
				DK *int `json:"DK,omitempty"`
				EC *int `json:"EC,omitempty"`
				EE *int `json:"EE,omitempty"`
				EG *int `json:"EG,omitempty"`
				ES *int `json:"ES,omitempty"`
				FI *int `json:"FI,omitempty"`
				FR *int `json:"FR,omitempty"`
				GB *int `json:"GB,omitempty"`
				GH *int `json:"GH,omitempty"`
				GR *int `json:"GR,omitempty"`
				GT *int `json:"GT,omitempty"`
				HK *int `json:"HK,omitempty"`
				HN *int `json:"HN,omitempty"`
				HU *int `json:"HU,omitempty"`
				ID *int `json:"ID,omitempty"`
				IE *int `json:"IE,omitempty"`
				IL *int `json:"IL,omitempty"`
				IN *int `json:"IN,omitempty"`
				IT *int `json:"IT,omitempty"`
				JP *int `json:"JP,omitempty"`
				LT *int `json:"LT,omitempty"`
				LV *int `json:"LV,omitempty"`
				MU *int `json:"MU,omitempty"`
				MX *int `json:"MX,omitempty"`
				MY *int `json:"MY,omitempty"`
				MZ *int `json:"MZ,omitempty"`
				NL *int `json:"NL,omitempty"`
				NO *int `json:"NO,omitempty"`
				NZ *int `json:"NZ,omitempty"`
				PE *int `json:"PE,omitempty"`
				PH *int `json:"PH,omitempty"`
				PL *int `json:"PL,omitempty"`
				PT *int `json:"PT,omitempty"`
				PY *int `json:"PY,omitempty"`
				RU *int `json:"RU,omitempty"`
				SA *int `json:"SA,omitempty"`
				SE *int `json:"SE,omitempty"`
				SG *int `json:"SG,omitempty"`
				SI *int `json:"SI,omitempty"`
				SK *int `json:"SK,omitempty"`
				TH *int `json:"TH,omitempty"`
				TR *int `json:"TR,omitempty"`
				TW *int `json:"TW,omitempty"`
				UG *int `json:"UG,omitempty"`
				US *int `json:"US,omitempty"`
				VE *int `json:"VE,omitempty"`
				ZA *int `json:"ZA,omitempty"`
			} `json:"display_priorities,omitempty"`
			DisplayPriority *int    `json:"display_priority,omitempty"`
			LogoPath        *string `json:"logo_path,omitempty"`
			ProviderId      *int    `json:"provider_id,omitempty"`
			ProviderName    *string `json:"provider_name,omitempty"`
		} `json:"results,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r ProviderTvListResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ProviderTvListResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ProviderTvListResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// ProvidersMovieListWithResponse request returning *ProvidersMovieListResponse
func (c *ClientWithResponses) ProvidersMovieListWithResponse(ctx context.Context, params *ProvidersMovieListParams, reqEditors ...RequestEditorFn) (*ProvidersMovieListResponse, error) {
	rsp, err := c.ProvidersMovieList(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseProvidersMovieListResponse(rsp)
}

// ProvidersAvailableRegionsWithResponse request returning *ProvidersAvailableRegionsResponse
func (c *ClientWithResponses) ProvidersAvailableRegionsWithResponse(ctx context.Context, params *ProvidersAvailableRegionsParams, reqEditors ...RequestEditorFn) (*ProvidersAvailableRegionsResponse, error) {
	rsp, err := c.ProvidersAvailableRegions(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseProvidersAvailableRegionsResponse(rsp)
}

// ProviderTvListWithResponse request returning *ProviderTvListResponse
func (c *ClientWithResponses) ProviderTvListWithResponse(ctx context.Context, params *ProviderTvListParams, reqEditors ...RequestEditorFn) (*ProviderTvListResponse, error) {
	rsp, err := c.ProviderTvList(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseProviderTvListResponse(rsp)
}

// ParseProvidersMovieListResponse parses an HTTP response from a ProvidersMovieListWithResponse call
func ParseProvidersMovieListResponse(rsp *http.Response) (*ProvidersMovieListResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ProvidersMovieListResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Results *[]struct {
				DisplayPriorities *struct {
					AE *int `json:"AE,omitempty"`
					AR *int `json:"AR,omitempty"`
					AT *int `json:"AT,omitempty"`
					AU *int `json:"AU,omitempty"`
					BE *int `json:"BE,omitempty"`
					BG *int `json:"BG,omitempty"`
					BO *int `json:"BO,omitempty"`
					BR *int `json:"BR,omitempty"`
					CA *int `json:"CA,omitempty"`
					CH *int `json:"CH,omitempty"`
					CL *int `json:"CL,omitempty"`
					CO *int `json:"CO,omitempty"`
					CR *int `json:"CR,omitempty"`
					CV *int `json:"CV,omitempty"`
					CZ *int `json:"CZ,omitempty"`
					DE *int `json:"DE,omitempty"`
					DK *int `json:"DK,omitempty"`
					EC *int `json:"EC,omitempty"`
					EE *int `json:"EE,omitempty"`
					EG *int `json:"EG,omitempty"`
					ES *int `json:"ES,omitempty"`
					FI *int `json:"FI,omitempty"`
					FR *int `json:"FR,omitempty"`
					GB *int `json:"GB,omitempty"`
					GH *int `json:"GH,omitempty"`
					GR *int `json:"GR,omitempty"`
					GT *int `json:"GT,omitempty"`
					HK *int `json:"HK,omitempty"`
					HN *int `json:"HN,omitempty"`
					HU *int `json:"HU,omitempty"`
					ID *int `json:"ID,omitempty"`
					IE *int `json:"IE,omitempty"`
					IL *int `json:"IL,omitempty"`
					IN *int `json:"IN,omitempty"`
					IT *int `json:"IT,omitempty"`
					JP *int `json:"JP,omitempty"`
					LT *int `json:"LT,omitempty"`
					LV *int `json:"LV,omitempty"`
					MU *int `json:"MU,omitempty"`
					MX *int `json:"MX,omitempty"`
					MY *int `json:"MY,omitempty"`
					MZ *int `json:"MZ,omitempty"`
					NL *int `json:"NL,omitempty"`
					NO *int `json:"NO,omitempty"`
					NZ *int `json:"NZ,omitempty"`
					PE *int `json:"PE,omitempty"`
					PH *int `json:"PH,omitempty"`
					PL *int `json:"PL,omitempty"`
					PT *int `json:"PT,omitempty"`
					PY *int `json:"PY,omitempty"`
					RU *int `json:"RU,omitempty"`
					SA *int `json:"SA,omitempty"`
					SE *int `json:"SE,omitempty"`
					SG *int `json:"SG,omitempty"`
					SI *int `json:"SI,omitempty"`
					SK *int `json:"SK,omitempty"`
					TH *int `json:"TH,omitempty"`
					TR *int `json:"TR,omitempty"`
					TW *int `json:"TW,omitempty"`
					UG *int `json:"UG,omitempty"`
					US *int `json:"US,omitempty"`
					VE *int `json:"VE,omitempty"`
					ZA *int `json:"ZA,omitempty"`
				} `json:"display_priorities,omitempty"`
				DisplayPriority *int    `json:"display_priority,omitempty"`
				LogoPath        *string `json:"logo_path,omitempty"`
				ProviderId      *int    `json:"provider_id,omitempty"`
				ProviderName    *string `json:"provider_name,omitempty"`
			} `json:"results,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseProvidersAvailableRegionsResponse parses an HTTP response from a ProvidersAvailableRegionsWithResponse call
func ParseProvidersAvailableRegionsResponse(rsp *http.Response) (*ProvidersAvailableRegionsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ProvidersAvailableRegionsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Results *[]struct {
				EnglishName *string `json:"english_name,omitempty"`
				Iso31661    *string `json:"iso_3166_1,omitempty"`
				NativeName  *string `json:"native_name,omitempty"`
			} `json:"results,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseProviderTvListResponse parses an HTTP response from a ProviderTvListWithResponse call
func ParseProviderTvListResponse(rsp *http.Response) (*ProviderTvListResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ProviderTvListResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Results *[]struct {
				DisplayPriorities *struct {
					AE *int `json:"AE,omitempty"`
					AR *int `json:"AR,omitempty"`
					AT *int `json:"AT,omitempty"`
					AU *int `json:"AU,omitempty"`
					BE *int `json:"BE,omitempty"`
					BG *int `json:"BG,omitempty"`
					BO *int `json:"BO,omitempty"`
					BR *int `json:"BR,omitempty"`
					CA *int `json:"CA,omitempty"`
					CH *int `json:"CH,omitempty"`
					CL *int `json:"CL,omitempty"`
					CO *int `json:"CO,omitempty"`
					CR *int `json:"CR,omitempty"`
					CV *int `json:"CV,omitempty"`
					CZ *int `json:"CZ,omitempty"`
					DE *int `json:"DE,omitempty"`
					DK *int `json:"DK,omitempty"`
					EC *int `json:"EC,omitempty"`
					EE *int `json:"EE,omitempty"`
					EG *int `json:"EG,omitempty"`
					ES *int `json:"ES,omitempty"`
					FI *int `json:"FI,omitempty"`
					FR *int `json:"FR,omitempty"`
					GB *int `json:"GB,omitempty"`
					GH *int `json:"GH,omitempty"`
					GR *int `json:"GR,omitempty"`
					GT *int `json:"GT,omitempty"`
					HK *int `json:"HK,omitempty"`
					HN *int `json:"HN,omitempty"`
					HU *int `json:"HU,omitempty"`
					ID *int `json:"ID,omitempty"`
					IE *int `json:"IE,omitempty"`
					IL *int `json:"IL,omitempty"`
					IN *int `json:"IN,omitempty"`
					IT *int `json:"IT,omitempty"`
					JP *int `json:"JP,omitempty"`
					LT *int `json:"LT,omitempty"`
					LV *int `json:"LV,omitempty"`
					MU *int `json:"MU,omitempty"`
					MX *int `json:"MX,omitempty"`
					MY *int `json:"MY,omitempty"`
					MZ *int `json:"MZ,omitempty"`
					NL *int `json:"NL,omitempty"`
					NO *int `json:"NO,omitempty"`
					NZ *int `json:"NZ,omitempty"`
					PE *int `json:"PE,omitempty"`
					PH *int `json:"PH,omitempty"`
					PL *int `json:"PL,omitempty"`
					PT *int `json:"PT,omitempty"`
					PY *int `json:"PY,omitempty"`
					RU *int `json:"RU,omitempty"`
					SA *int `json:"SA,omitempty"`
					SE *int `json:"SE,omitempty"`
					SG *int `json:"SG,omitempty"`
					SI *int `json:"SI,omitempty"`
					SK *int `json:"SK,omitempty"`
					TH *int `json:"TH,omitempty"`
					TR *int `json:"TR,omitempty"`
					TW *int `json:"TW,omitempty"`
					UG *int `json:"UG,omitempty"`
					US *int `json:"US,omitempty"`
					VE *int `json:"VE,omitempty"`
					ZA *int `json:"ZA,omitempty"`
				} `json:"display_priorities,omitempty"`
				DisplayPriority *int    `json:"display_priority,omitempty"`
				LogoPath        *string `json:"logo_path,omitempty"`
				ProviderId      *int    `json:"provider_id,omitempty"`
				ProviderName    *string `json:"provider_name,omitempty"`
			} `json:"results,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}
